### ISSUE TITLE
Is resigning possible?

### ISSUE THREAD

**Issue by Taureon** [SebLague/Chess-Challenge#1]
I want to make my bot resign, but I can't find a method of doing that in the [documentation](https://seblague.github.io/chess-coding-challenge/documentation/#piece-type-enum).

**Comment by anko** [comment]
> let time run out

See also https://github.com/SebLague/Chess-Challenge/issues/6

**Comment by SebLague** [comment]
If you return Move.Null it will forfeit the game due to illegal move, which I guess you could think of as resigning. I recommend you let the bot keep playing until mate though.
