### ISSUE TITLE
How can I get the list of all the moves made?

### ISSUE THREAD

**Issue by MathabsUnity** [SebLague/Chess-Challenge#100]
How can I get the list of all the moves made (1. e4 e5 2. Nf3 Nc6...)?

**Comment by AugsEU** [comment]
The documentation doesn't have that function. Looks like you would need to keep track of that in the chess bot. I don't see why moves in the past would matter anyway.

**Comment by dr-vortex** [comment]
Duplicate of #92

**Comment by SebLague** [comment]
Closing as duplicate
