### ISSUE TITLE
It is possible for the human to input an illegal move on behalf of the bot, crashing the program.

### ISSUE THREAD

**Issue by AugsEU** [SebLague/Chess-Challenge#102]
Reproduction steps:

1) Make very slow bot
2) Play "Human Vs Bot"
3) Make a move
4) While the bot is thinking, start dragging your pieces around.
5) The console will say the bot made an illegal move.
6) Program sometimes crashes?

**Comment by CaptainDeathead** [comment]
Is it possible for you to reduce thinking depth / time, same thing happened to me and I reduced the depth and it still performed about as well and was a lot speedier. (Note this will affect end game performance)

**Comment by SebLague** [comment]
Thanks, this is fixed in latest patch (V1.11)
