### ISSUE TITLE
Are multiple submissions allowed?

### ISSUE THREAD

**Issue by Henry-314159** [SebLague/Chess-Challenge#103]

**Comment by ufrshubham** [comment]
This isn't an issue and can be closed. There is already a discussion regarding this in the `Discussion` tab.

**Comment by SebLague** [comment]
I've updated rules on this in the readme:
You may submit a maximum of two entries.
Please only submit a second entry if it is significantly different from your first bot (not just a minor tweak).
Note: you will need to log in with a second Google account if you want submit a second entry.
