### ISSUE TITLE
How do I get FEN from rank & file?

### ISSUE THREAD

**Issue by Vanny-Chuck** [SebLague/Chess-Challenge#106]
I need to get the FEN of a Square. I went digging but, sadly ended up with invalid namespaces.

**Comment by MinekPo1** [comment]
The way I approached this problem is:

```C#
$"{(char)('a' + squarei % 8)}{squarei / 8 + 1}"
```

**Comment by Vanny-Chuck** [comment]
squarei?

**Comment by MinekPo1** [comment]
oh sorry lol. squarei stands for square index, I forgot to change it to directly fit your need.

**Comment by Vanny-Chuck** [comment]
as in rank?

**Comment by MinekPo1** [comment]
I updated my comment.

**Comment by Vanny-Chuck** [comment]
Thnx
