### ISSUE TITLE
Building and Running

### ISSUE THREAD

**Issue by CharlesBeverly** [SebLague/Chess-Challenge#107]
I was wondering how one simply "builds and runs" the project. In the read me it says that you simply need to "build and run" the project, but for the life of me I cannot figure out how, I'm no stranger to computer programing but this step has me baffled and if it is causing me this much strife then others who have absolutely no experience will be sure to be frustrated.

**Comment by regulus79** [comment]
I am inexperienced with .NET applications, but after some googling, this is what worked for me:

If you already have .NET installed, then I believe you can simply navigate to the `./Chess-Challenge/` folder, and run
`dotnet build`
and then
`dotnet run`

I am on Arch Linux, but I believe this should work for any OS.

**Comment by 0mlml** [comment]
I'm also on linux but if you're on windows, I'd try the install script from microsoft's website:
https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1

Then you can just run `dotnet run` in the folder with the `.csproj` file.
