### ISSUE TITLE
Possible optimization issue with the move generation approarch

### ISSUE THREAD

**Issue by pedro15** [SebLague/Chess-Challenge#109]
In the example code of MyBot
```csharp﻿
using ChessChallenge.API;
public class MyBot : IChessBot
{
    public Move Think(Board board, Timer timer)
    {
        Move[] moves = board.GetLegalMoves();
        return moves[0];
    }
}
```

you alocate Move[] array to the GetLegalMoves() method, that is fine, but it comes with a trick, those moves are heap allocated and can run into performance issues, 

the way it should be done is by allocating the moves in the stack, and you pass the Moves[] as a ref parameter, like:
```csharp﻿
using ChessChallenge.API;
public class MyBot : IChessBot
{
    public Move Think(Board board, Timer timer)
    {
         System.Span<Move> moves = stackalloc Move[256];
         board.GetLegalMoves(ref moves);
        return moves[0];
    }
}
```

but that will require changes to the core of the API, so please take that into consideration, thank you!

**Comment by SebLague** [comment]
Thanks for the suggestion! This is obviously better, but I decided to favour simplicity over performance for this challenge.
