### ISSUE TITLE
How can I get a list of all of my opponents pieces?

### ISSUE THREAD

**Issue by kittymuffin** [SebLague/Chess-Challenge#114]
Right now I'm using GetPieceList(0, !IsWhiteToMove) to find a list of my opponent's pieces but the method returns an the object type instead of an array or list of pieces and I can't use GetPieceList().Count or anything.
-I'm on the newest version of the project d have checked the comment on the introductory video
-I haven't seen any other issue like this on the issues section

**Comment by JoChLi** [comment]
you can use BitboardHelper.GetNumberOfSetBits(board.WhitePiecesBitboard) to get the number of white pieces or BitboardHelper.GetNumberOfSetBits(board.BlackPiecesBitboard) to get the number of black pieces

**Comment by kittymuffin** [comment]
Thanks (:
