### ISSUE TITLE
Cannot bring Move variable out of a foreach loop

### ISSUE THREAD

**Issue by Artem111A** [SebLague/Chess-Challenge#116]
using ChessChallenge.API;
using System;

public class MyBot : IChessBot
{
    const PieceType Pawn = (PieceType)1;
    const PieceType Knight = (PieceType)2;
    const PieceType Bishop = (PieceType)3;
    const PieceType Rook = (PieceType)4;
    const PieceType Queen = (PieceType)5;

    public Move Think(Board board, Timer timer)

    {
        bool IsBotWhite = board.IsWhiteToMove;
        Move[] FirstDepthMoves = board.GetLegalMoves();

        Random rng = new();
        Move moveToPlay = FirstDepthMoves[rng.Next(FirstDepthMoves.Length)];
        int PositionEvalueation = 0;
         Move FirstDepth;
         Move SecondDepth;
        foreach (Move move in FirstDepthMoves)
        {
            
            //Try a move
            board.MakeMove(move);
             
            
                
            
            Move[] SecondDepthMoves = board.GetLegalMoves();
            foreach (Move move1 in SecondDepthMoves)
            {
                // Try a second move
                board.MakeMove(move1);
                    
                int CurrentEvaluation1 = EvaluatePosition(board, !IsBotWhite);
                // If move be good, then we memorize it
                if (CurrentEvaluation1 > PositionEvalueation)
                {
                    //Record this to then play + for seeing its thinking procces in Console
                    FirstDepth = move;
                    SecondDepth = move1;

                    PositionEvalueation = CurrentEvaluation1;
                }
                
               
                board.UndoMove(move1);
            }
            
            
            board.UndoMove(move);
        }
        // Here it tells me that It didnt get the value assigned to FirstDepth and SecondDepth from foreach loop
        //Idk what to do else about it
        Console.WriteLine(FirstDepth);
        board.MakeMove(FirstDepth);
        Console.WriteLine(EvaluatePosition(board, !IsBotWhite));
        Console.WriteLine(SecondDepth);
        board.MakeMove(SecondDepth);
        Console.WriteLine(EvaluatePosition(board, !IsBotWhite));
        board.UndoMove(SecondDepth); 
        board.UndoMove(FirstDepth);
        return FirstDepth;
    }

    
   
    
    int EvaluatePosition(Board board, bool IsWhite)
    {
   
        //the E stands for Enemy
        PieceList Pawns = board.GetPieceList(pieceType: Pawn, white: IsWhite);
        PieceList Knights = board.GetPieceList(pieceType: Knight, white: IsWhite);
        PieceList Bishops = board.GetPieceList(pieceType: Bishop, white: IsWhite);
        PieceList Rooks = board.GetPieceList(pieceType: Rook, white: IsWhite);
        PieceList Queens = board.GetPieceList(pieceType: Queen, white: IsWhite);
        bool IsWhiteE = !IsWhite;
        PieceList PawnsE = board.GetPieceList(pieceType: Pawn, white: IsWhiteE);
        PieceList KnightsE = board.GetPieceList(pieceType: Knight, white: IsWhiteE);
        PieceList BishopsE = board.GetPieceList(pieceType: Bishop, white: IsWhiteE);
        PieceList RooksE = board.GetPieceList(pieceType: Rook, white: IsWhiteE);
        PieceList QueensE = board.GetPieceList(pieceType: Queen, white: IsWhiteE);
        int TotalEval = ((Pawns.Count * 1) + (Knights.Count * 3) + (Bishops.Count * 3) + (Rooks.Count * 5) + (Queens.Count * 9)) - ((PawnsE.Count * 1) + (KnightsE.Count * 3) + (BishopsE.Count * 3) + (RooksE.Count * 5) + (QueensE.Count * 9));

        if (board.IsDraw())
        {
            TotalEval = -100;
        }
        else if (board.IsInCheckmate())
        {
            TotalEval = 100;
        }
        if (board.IsInCheck())
        {
            TotalEval = TotalEval +  1;
        } 
        
        return -TotalEval;
    }
}

Here is the code above
For some reason the foreach loop doesnt want to assign the values to the variables, which makes it tell me that I cannot use unassigned variables

**Comment by SebLague** [comment]
The problem is that the compiler can't guarantee ahead of time that the code that assigns FirstDepth and SecondDepth will be run. To get around this you can give them default values like so:
Move FirstDepth = Move.NullMove;
Move SecondDepth = Move.NullMove;
