### ISSUE TITLE
Rule Ambiguity and External Files

### ISSUE THREAD

**Issue by 21maskeand** [SebLague/Chess-Challenge#117]
If I decide to use a machine learning approach, am I allowed to train my neural network outside of the my bot file and then just copy paste the weights and biases in?

**Comment by Odin7094** [comment]
"Note: you may create additional scripts for testing/training your bot, but only the MyBot.cs file will be submitted, so it must be able to run without them."
Is that what you asked for?
Remember though, such approach will max out your tokens very quickly.

**Comment by 21maskeand** [comment]
Kinda, I'm just dumb and didn't see the closed issue section. A similar question was already answered over there.
