### ISSUE TITLE
Rules dont ban functions like nameof() for storing data. 

### ISSUE THREAD

**Issue by MrRaV0** [SebLague/Chess-Challenge#12]
A string that is constructed using "" has a token-count that depends on its size. I would assume that this is done to avoid freely storing lots of data. 

This token cost can be avioded by putting your data in the name of a function, and then returning nameof() within that funtion.

**Comment by CeniusM** [comment]
Sience a name is a single token, could You in theory make the stockfish neural network wheights and biases into a single string and load that for the first round and use that as your evaluation?

**Comment by SebLague** [comment]
That's a great point thank you. I'll add it to the rules!

**Comment by VictorSohier** [comment]
Dammit, I was thinking of abusing this with an emulator (not that it was going to fit, I'm surprised how much I fit in though). BTW, this isn't unbounded, it is merely a more than intended.
