### ISSUE TITLE
Capturing king considered as a legal move 

### ISSUE THREAD

**Issue by sachavincent** [SebLague/Chess-Challenge#129]
I'll start by saying I'm not a chess expert so I might have misunderstood something here.

In any case, I have modified the ChallengerController class at the line 93 so the board loads this particular FEN : 8/8/8/8/1k6/1Q6/8/5K2 w - - 0 1.

When I play the default evil bot which is only looking through the moves provided by the function Board.GetLegalMoves(), the bot captures my king and ends the game, without any illegal moves being registered. The result is simply a stalemate according to the console.. 

Is this intended behavior?

**Comment by SebLague** [comment]
Hi, this is an invalid position because black is in check but it is white's turn to move. If you change the 'w' at the end of the fen to a 'b' to make it black's move, it should work fine.

**Comment by sachavincent** [comment]
Hi,

Alright, thanks for clarifying my issue. As I said, not an expert xD
