### ISSUE TITLE
Can I use .NET 7?

### ISSUE THREAD

**Issue by just-a-hriday** [SebLague/Chess-Challenge#13]
Is it fine if I use .NET 7?

**Comment by Alfred-Jijo** [comment]
It should matter what you have both installed if thats what you meant you probably need .Net 6 but if you have both it shouldnt effect anything.

If you find the .csproj file you should see this:
```csproj
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Chess_Challenge</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
```

in the `TargetFramework` you can see its automatically net6.0 and I have both 6.0 and 7.0 installed

**Comment by just-a-hriday** [comment]
> It should matter what you have both installed if thats what you meant you probably need .Net 6 but if you have both it shouldnt effect anything.
> 
> If you find the .csproj file you should see this:
> 
> ```
>   <PropertyGroup>
>     <OutputType>Exe</OutputType>
>     <TargetFramework>net6.0</TargetFramework>
>     <RootNamespace>Chess_Challenge</RootNamespace>
>     <ImplicitUsings>disable</ImplicitUsings>
>     <Nullable>enable</Nullable>
>     <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
>   </PropertyGroup>
> ```
> 
> in the `TargetFramework` you can see its automatically net6.0 and I have both 6.0 and 7.0 installed

That's not my question.

**Comment by CREAsTIVE** [comment]
> That's not my question. I asked if it would be against the rules to use net7.0.

Just read the tules. (spoiler: no)

**Comment by just-a-hriday** [comment]
> Just read the rules. (spoiler: no)

The rules don't mention the .net version at all. The instructions ask you to install .net 6, but that doesn't mean anything.

**Comment by lucasmeneghin** [comment]
I guess as long as your code compiles with .net 6 it should be fine, if not, then no
Of course the only person who can answer is Sebastian but i dont think he well change compiler depending on the submission

**Comment by SebLague** [comment]
Hi, I'll be running submissions with .NET 6 so it needs to work with that. So long as you test it before submitting though, you're welcome to work with .NET 7
