### ISSUE TITLE
Tokenizer Does not Ignore Closing Brace Token

### ISSUE THREAD

**Issue by Westly-Bouchard** [SebLague/Chess-Challenge#132]
Currently, lines like `Move[] moves = board.GetLegalMoves();` are not correctly tokenized according to the readme of the challenge.

`TokenCounter.cs` defines that closing braces, brackets, and parentheses are to be ignored, as a pair is to be counted as one token. Following this, the line above should contain 8 tokens. However the tokenizer currently counts 9.

Here is how I have confirmed this:
When I run this `MyBot.cs` file
```cs
using ChessChallenge.API;

public class MyBot : IChessBot
{
    public Move Think(Board board, Timer timer)
    {
        Move[] moves = board.GetLegalMoves();

        int[] test;

        return moves[0];
    }
}
```
The tokenizer counts 35 tokens: <img width="286" alt="Screenshot 2023-07-21 at 10 38 50 PM" src="https://github.com/SebLague/Chess-Challenge/assets/57117414/032c951d-e582-4b8d-b4e6-dff2ace3cfa2">

However, when I change the array declaration `int[] test;` to a variable declaration `int test;`

The number of tokens drops by 2: <img width="323" alt="Screenshot 2023-07-21 at 10 40 19 PM" src="https://github.com/SebLague/Chess-Challenge/assets/57117414/fa59e72d-24ba-4057-9754-1fda56abda00">

This means that both the open and close braces are being counted when they should be counted as a pair.

From what I can tell looking at the source code I'm not sure why this is happening, so if anyone else is able to reproduce this issue, please let me know. I'm not sure if this is bad etiquette but I would love if @SebLague could take a look at this and see if he could reproduce it as well.  

I am currently running dotnet `6.0.412` in case that matters.
I don't see this being a platform thing but just in case: I'm running on a apple silicon macbook on macos Sonoma beta

**Comment by harrisi** [comment]
This is a fun token. So the open and close brackets are being counted correctly, i.e. `[` is counted but `]` is not, but C# has a token called `OmittedArraySizeExpressionToken`, which is a token to specify that the array size is omitted. I'm not sure if it's correct to ignore this token, since I think you could abuse this in a clever way. `int[,] test;` has the following tokens:

```C#
IntKeyword  int
OpenBracketToken  [
OmittedArraySizeExpressionToken  
OmittedArraySizeExpressionToken  
// ignored: CloseBracketToken
IdentifierToken  test
```

which, if `OmittedArraySizeExpressionToken` is not counted, means you could abuse different dimensionality of variables to compute/encode things without accruing excess tokens.

**Comment by QuinnCG** [comment]
I'm using `v1.1` and my curly braces and parenthesizes are being counted on a once-per-pair basis.

**Comment by Westly-Bouchard** [comment]
That would explain it, thank you very much. I've never heard of a token that represents the lack of something. Gonna go ahead and close this issue.
