### ISSUE TITLE
GetLegalMoves returning invalid moves

### ISSUE THREAD

**Issue by BillyOwen** [SebLague/Chess-Challenge#136]
If the board is in this state: "r1bqkbnr/pppppppp/n7/8/8/N2nPP2/PPPP1P1P/2BQKB1R w KQk - 10 6" then GetLegalMoves() returns 'e1d2' and 'e1e2' as valid moves. The actual legal moves are 'c2d3', 'e1e2' and 'f1d3'.

**Comment by BillyOwen** [comment]
I just used Board.CreateBoardFromFEN("r1bqkbnr/pppppppp/n7/8/8/N2nPP2/PPPP1P1P/2BQKB1R w KQk - 10 6") and it is returning the correct moves, so I am now confused as to what's going on

**Comment by BillyOwen** [comment]
I've done some more testing and there is definitely a bug, I just don't know what.

```
if (board.GetFenString() == "r1bqkbnr/pppppppp/n7/8/8/N2nPP2/PPPP1P1P/2BQKB1R w KQk - 10 6")
        {
            
            Board new_one = Board.CreateBoardFromFEN(board.GetFenString());
            Console.WriteLine("New board from fen:");
            foreach (Move move in new_one.GetLegalMoves())
            {
                Console.Write(move.ToString());
            }

            Console.WriteLine("Old board:");
            foreach (Move move in board.GetLegalMoves())
            {
                Console.Write(move.ToString());
            }
        }
```

Outputs: 
New board from fen:
Move: 'e1e2'Move: 'f1d3'Move: 'c2d3'Old board:
Move: 'e1d2'Move: 'e1e2'

Somehow the board is in a corrupted state

**Comment by BillyOwen** [comment]
Yes! The AllPiecesBitboards are different:

New board:
18302348510172393404
Old board:
18302348518770847676

**Comment by noahshi** [comment]
I'm having this problem too. In the endgame, GetLegalMoves is returning a bunch of illegal moves for me.

In the position "3n4/1p1k4/5Q2/p1p5/P7/1P6/5PPP/3R2K1 b - - 1 35", GetLegalMoves returned the illegal move h4h2, which my bot promptly played and claimed it was checkmate. Then I got a System.IO.IOException.

**Comment by BillyOwen** [comment]
Whoops, turns out there was a bug in my code, I was returning from a function before calling UndoMove
