### ISSUE TITLE
Evaluating Performance of bot faster

### ISSUE THREAD

**Issue by i-am-abhi747** [SebLague/Chess-Challenge#138]
Playing 1000 games with "base" bot is excellent way to evaluate performance. But currently playing 1000 games takes forever.
I would like to be play multiple games in parallel and disable playing UI on demand.

**Comment by GheorgheMorari** [comment]
Hi, I've made this implementation: https://github.com/GheorgheMorari/Chess-Challenge

**Comment by austin-owensby** [comment]
@GheorgheMorari That's super useful! Now I don't have to wait ~35 minutes each time.

I think it would be worth it to make this as a PR to the repo!

**Comment by mcthouacbb** [comment]
Is the "base" bot the evil bot, or is it something else?

**Comment by i-am-abhi747** [comment]
"base" bot can be anything for just reference, in my case it's my basic bot.

**Comment by i-am-abhi747** [comment]
@GheorgheMorari, Thanks!
