### ISSUE TITLE
board.GetPiece() doesn't return correct piece after board.MakeMove()

### ISSUE THREAD

**Issue by lemz1** [SebLague/Chess-Challenge#139]
im using EvilBots MoveIsCheckmate as an example here:
```
    // Test if this move gives checkmate
    private bool MoveIsCheckmate(Board board, Move move)
    {
        board.MakeMove(move);
        Piece piece = board.GetPiece(move.TargetSquare); // i added this line for debugging this issue
        bool isMate = board.IsInCheckmate();
        board.UndoMove(move);
        return isMate;
    }
```
if you use the debugger in Visual Studio and step into this function, you can see that the variable `piece` is `null`, even though it should be the piece you moved.
im not sure why this happens.
what i do know is that if you go much deeper in the variables of `board` and look at the `Squares`, you can see that the piece you moved is at the correct square. So i imagine that there's somehow something not being done in the board.GetPiece() function

**Comment by SebLague** [comment]
Hi, this was a bug in the original version. Please make sure you have the latest version (you can see the Change Log section in the readme for more details).

**Comment by lemz1** [comment]
oops, i didnt fork the project so i didnt have the latest version.
my bad.
thanks for the fix

**Comment by SebLague** [comment]
No worries, sorry for the bug!
