### ISSUE TITLE
Illegal move on player move when bot is to play

### ISSUE THREAD

**Issue by DanielMo09** [SebLague/Chess-Challenge#143]
I know, it is a bug you can avoid but I wanted to try to premove, didn't know it did not exist and it gave me a illegal move error.

**Comment by CaptainDeathead** [comment]
This has happened to a few people; it usually happens when you bot takes a while to make a move. I just reduced search time and that fixed it but would also reduce performance. I'm sure Sebastion is aware of it.

**Comment by SebLague** [comment]
Input bug for human player should be fixed now (v1.11)
