### ISSUE TITLE
Project Doesnt build on Mac

### ISSUE THREAD

**Issue by EvilDarkSoul** [SebLague/Chess-Challenge#144]
MacOS Ventura 13.4 (22F66)
Visual Studio 2022 v17.6.1 (build 452)
.Net Version 6.0.412 & 7.0.306

Whenever i try and build it normally in VS it says "Build Failed. Check Build log"
If i build it through terminal with "msbuild" it says 

`Done Building Project "/Users/myname/Desktop/Chess-Challenge/Chess-Challenge.sln" (default targets) -- FAILED.

Build FAILED.

"/Users/myname/Desktop/Chess-Challenge/Chess-Challenge.sln" (default target) (1) ->
"/Users/myname/Desktop/Chess-Challenge/Chess-Challenge/Chess-Challenge.csproj" (default target) (2) ->
(GetReferenceAssemblyPaths target) ->
  /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1232,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET5.0 or higher. Update Visual Studio and/or your .NET SDK. [/Users/myname/Desktop/Chess-Challenge/Chess-Challenge/Chess-Challenge.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.68`

which doesnt make sense because its its the most recent version of VS and ive got the correct version of .Net

**Comment by moredatapls** [comment]
It build on my Mac. I think it's a configuration issue on your side, did you check if you configured the correct .NET version in VS? Also, what's the output of `dotnet --list-sdks`?

**Comment by EvilDarkSoul** [comment]
1. yes i had configured it in VS but every time i close preferences it resets and then cant find it. so i guess thats the problem. now to fix that
2. "6.0.412 [/usr/local/share/dotnet/sdk]
7.0.306 [/usr/local/share/dotnet/sdk]"

**Comment by Plerx2493** [comment]
Make sure to use DotNet Core and dont use Mono. Its mentioned in your folder paths

**Comment by EvilDarkSoul** [comment]
I am pretty sure it keeps using mono because it resets from using .Net every time i close preferences

**Comment by RaxMoth** [comment]
have you tried to just run it with dotnet run ?

**Comment by EvilDarkSoul** [comment]
That did actually work. its a bit annoying to do but it works
