### ISSUE TITLE
Changes made with Board.MakeMove not reflected in Board.GetPiece

### ISSUE THREAD

**Issue by rokbok** [SebLague/Chess-Challenge#146]
`Board.GetPiece` uses `Board.pieces` to determine its return value. However, `Board.pieces` is never updated after board creation, including not upon `Board.MakeMove` or `Board.UndoMove` calls. Therefore, `GetPiece` will always reflect the initial state, not the current state.

The same issue appears to apply to `allPieceLists` and `validPieceLists`.

**Comment by draeg82** [comment]
Wasn't this resolved on last night's patch?  I had the same issue until I updated to the most up to date version

**Comment by haase-laurenz** [comment]
yeah. Just get the new version. Had the same issue

**Comment by rokbok** [comment]
You are right, should've checked first
