### ISSUE TITLE
White Pawn being identified as black with name in Board.GetPiece(Square)  and Board.GetPiece(Square).IsWhite

### ISSUE THREAD

**Issue by draeg82** [SebLague/Chess-Challenge#148]

**Comment by draeg82** [comment]
Not every pawn.  Some are misidentified as the opposite colour, but not every.  for example starting as white, e2 pawn is black.

**Comment by SebLague** [comment]
Hi, are you using V1.1 of the project? (the original version had a bug in the GetPiece function -- see changelog in readme for more details).

**Comment by draeg82** [comment]
Yes I'm on 1.1 - I pulled from the Repo again this morning with no new changes that I can see.  I pulled initially last night after having a problem with test moves not reflecting in Board.GetPieces()

**Comment by draeg82** [comment]
See the pawn in position E6 for an example as well as debugging messages [here](https://photos.app.goo.gl/jVsr79yEZ5gWZFk5A)

**Comment by draeg82** [comment]
I'm such an idiot.  This is after evaluating a move.  the reason the pawn is black is because a black pawn captured white...
