### ISSUE TITLE
Function to check if a square is occupied and with which piece?

### ISSUE THREAD

**Issue by ayanchavand** [SebLague/Chess-Challenge#151]
is there a function in the API to do so?

**Comment by SebLague** [comment]
You can do board.GetPiece(square)

**Comment by CaptainDeathead** [comment]
I was just reading the documentation at: https://[seblague.github.io/chess-coding-challenge/documentation/](https://seblague.github.io/chess-coding-challenge/documentation/) and found that there is a function in the board called: GetPiece([Square](https://seblague.github.io/chess-coding-challenge/documentation/#square-struct) square)

**Comment by CaptainDeathead** [comment]
damm, i had just slower internet
