### ISSUE TITLE
Assets file project.assets.json not found.

### ISSUE THREAD

**Issue by ManosSef** [SebLague/Chess-Challenge#152]
I imported the project exactly as I downloaded it from this repository, and I'm getting this error when I try to run it:
`1>C:\Program Files\dotnet\sdk\7.0.306\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1004: Assets file 'C:\Users\User\Desktop\Other programs\Chess-Challenge\Chess-Challenge-main\Chess-Challenge-main\Chess-Challenge\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.`

**Comment by ManosSef** [comment]
For context, C:\Users\User\Desktop\Other programs\Chess-Challenge\Chess-Challenge-main\Chess-Challenge-main\Chess-Challenge is the folder I have the project in.

**Comment by CaptainDeathead** [comment]
Hi, can you try running `dotnet restore` in your command line?

**Comment by ManosSef** [comment]
That fixed it! Thanks!
