### ISSUE TITLE
MyBot.cs Cannot access the Repetition History

### ISSUE THREAD

**Issue by BeefyAndTheDucks** [SebLague/Chess-Challenge#153]
The bot you are making cannot access the Repetition History to try prevent repeated moves.

**Comment by CaptainDeathead** [comment]
To avoid this could you just make it check in your evaluation function for repetition and give it a low score if it is. something like `return 0;` for the score if it is repetition

**Comment by mcthouacbb** [comment]
It's accessed in board.IsDraw()

**Comment by BeefyAndTheDucks** [comment]
> To avoid this could you just make it check in your evaluation function for repetition and give it a low score if it is. something like `return 0;` for the score if it is repetition.
> 
> I just think that because if its looking 3+ moves ahead it should go fine assuming your using alpha beta pruning

I'm don't have any tokens left though...

**Comment by BeefyAndTheDucks** [comment]
> It's accessed in board.IsDraw()

Thank you!

**Comment by fasterik** [comment]
It's true that you can detect a repetition at the root with `board.IsDraw()`. However, reading the code it looks like the API does not update the repetition history while inside search. So if there is a piece sacrifice that leads to a repetition at ply 5, there is no way for the engine to detect it. Am I missing something?
