### ISSUE TITLE
The 50 move counter never resets

### ISSUE THREAD

**Issue by rokbok** [SebLague/Chess-Challenge#154]
Currently, the 50 move counter does never reset to 0 (should do so on capture / pawn move). I think this worked earlier

**Comment by mcthouacbb** [comment]
It actually does reset to 0, it just doesn't reset when in the search for some reason(Go to lines 262-272 of Chess-Challenge/src/Framework/Chess/Board/board.cs). It should definitely be updated in the search though, I'm not sure why it was avoided in the search.

**Comment by SebLague** [comment]
Fixed in latest patch, thank you!
