### ISSUE TITLE
EvaluateAllPieces() Identifies one teams Knight as None

### ISSUE THREAD

**Issue by JoelvdBrink** [SebLague/Chess-Challenge#157]
I wrote a very simple Minimax Algorythm, but no whether what I tried, My bot just seemed to keep giving away pieces for free, while it should obviously see that it throws away a knight/bishop/queen. Especially knights at the start were just thrown away, sacrificing it for a pawn. After scratching my head for hours, it seems like the EvaluateAllPieces() function incorrectly identifies one of the knights as None, giving the impression that one person is "6 pawns" ahead. Is this fixed with the Version 1.1 bug? The script below is my evaluation script which says there are 2 None pieces between the pawns and bishops. 

float Evaluation(Board board){

        float boardScore = 0.0F;

        PieceList[] Pieces = board.GetAllPieceLists();

        foreach(PieceList Piece in Pieces){
            boardScore += Piece.Count * EvaluatePiece(Piece[0].PieceType) * (Piece[0].IsWhite ? 1.0f: -1.0f);
        }
        
        boardScore = boardScore * (board.IsWhiteToMove ? 1.0f: -1.0f);

        if (boardScore != 0){
            foreach(PieceList Piece in Pieces){
                Debug.Write(Piece[0].PieceType);
                Debug.Write(Piece.Count);
                Debug.Write("  ");
            }
        }

        return boardScore;
    }

    int EvaluatePiece(PieceType piece){
        int[] PieceWeights = { 0, 100, 300, 325, 500, 900, 10000 };

        return PieceWeights[(int)piece];
    }

Sometimes (not always) it returns this to the console:
Pawn8  Knight2  Bishop2  Rook2  Queen1  King1  Pawn8  None2  Bishop2  Rook2  Queen1  King1

Edit: I am using version 1.0, I know there was one bug with GetPiece functions, is that the same bug that creates this behaviour?

**Comment by JoelvdBrink** [comment]
This sometimes is the output of the console: 

Pawn8  Knight2  Bishop2  Rook2  Queen1  King1  Pawn8  None2  Bishop2  Rook2  Queen1  King1

**Comment by CaptainDeathead** [comment]
Yeah i doubt its not working for anyone else, i agree with Joelvd. Maybe try print the fen string???

**Comment by SebLague** [comment]
I think this is related to the GetPiece bug, would you mind upgrading and seeing if the issue goes away? I haven't been able to reproduce on 1.1

Please note also that minimax alone will often make blunders due to horizon effect, so you might want to look into something like this: https://www.chessprogramming.org/Quiescence_Search
