### ISSUE TITLE
Add Documentation to the BitBoardHelper class

### ISSUE THREAD

**Issue by alice-lefebvre** [SebLague/Chess-Challenge#158]
Hey! Just a suggestion to add a bit of documentation to the bitboard format, like is the LSB supposed to be a8 or h1? is it row ordered?

For anyone wondering as well : it is row-ordered (works with Piece.Index), and the least significant bit is a1 (from what I can tell from the API)

**Comment by SebLague** [comment]
Thanks for the suggestion, I've added a bit more info to the docs that I hope will be helpful
