### ISSUE TITLE
Some error I am unable to fix

### ISSUE THREAD

**Issue by Alfred-Jijo** [SebLague/Chess-Challenge#16]
```
Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs(208,57,208,62): 
error CS7036: There is no argument given that corresponds to the required parameter 'isWhitePlayer' of 'MyBot.MyBot(bool)'
```

```cs
ChessPlayer CreatePlayer(PlayerType type)
{
            return type switch
            {                                            ∀ ∀ ∀ ∀ 
                PlayerType.MyBot => new ChessPlayer(new MyBot(), type, GameDurationMilliseconds),
                PlayerType.EvilBot => new ChessPlayer(new EvilBot(), type, GameDurationMilliseconds),
                _ => new ChessPlayer(new HumanPlayer(boardUI), type)
            };
 }
 ```
I have no idea what to do to fix this
Error is at (∀) On `MyBot()`

**Comment by R-Besson** [comment]
Did you modify the MyBot class in MyBot.cs? Because there is no "isWhitePlayer" argument required.
If you did edit it and added isWhitePlayer, make sure to include it when you are doing new MyBot(isWhitePlayer)...

**Comment by kiancn** [comment]
Questions:
1) does this error arise without you having touched any code?
2) does this happen instantly as the program starts - when does it happen?

**Comment by EikeSchwass** [comment]
You most likely added a constructor in your MyBot.cs class that takes a bool parameter `IsWhitePlayer`. Remove that constructor and the project should build. 
If that doesn't work you need to show us the MyBot.cs file
