### ISSUE TITLE
the use of Math.Max,Math.Min.

### ISSUE THREAD

**Issue by liadembin** [SebLague/Chess-Challenge#162]
reading the rules of the comp it appears that the use of the math library is forbidden? can anyone confirm?

**Comment by harrisi** [comment]
You can use these methods. `Math` is a class in the `System` namespace.

The easiest way to check is to just add the `using` statements with available namespaces and if your code compiles, it should be fine. Or look through the list of classes, structs, etc. here: https://learn.microsoft.com/en-us/dotnet/api/system?view=net-6.0 (note this is just `System` and doesn't show other things available in the other namespaces that are allowed).

**Comment by SebLague** [comment]
@harrisi is correct, you may use the Math class

**Comment by liadembin** [comment]
> @harrisi is correct, you may use the Math class
this question came up out of curiosity as it would allow the use of something like this: (new System.Net.Http.HttpClient()).GetStringAsync("http://localhost:8000/"); except instead of localhost it would be a server hosting stockfish. my code compiled as I'm accessing through System so technically it isn't a violation of the rules.

**Comment by harrisi** [comment]
The difference is `System.Net` is a separate namespace. The ability to use `System` doesn't mean you can use all the namespaces that start with `System`.

Further, there's no checking being done for which namespaces are being accessed. So really, you can do whatever you want, it's just that it won't count for the contest.
