### ISSUE TITLE
Console.Writeline() counts towards brain capacity. Is there another way you guys write to console for debugging.

### ISSUE THREAD

**Issue by natebursch** [SebLague/Chess-Challenge#163]
I am a newb and use WriteLine to quickly understand what's going on in my code.

Is there something else I should be doing? If not, can we make it so it doesn't write to brain capacity?

EDIT:
```                   
THIS LINE INCREASES BRAIN CAPACITY ->  Console.WriteLine("Removing a bad move" + moves[i]);
```

**Comment by RaxMoth** [comment]
what do you mean exactly ? 

Do you have an example ?

For example:
    Piece movingPiece = board.GetPiece(moveToPlay.StartSquare);
    int movingPieceValue = pieceValues[(int)movingPiece.PieceType];
    Console.WriteLine($"Chosen move: {moveToPlay}, Moving piece value: {movingPieceValue}");
    
    this gives you some good starting logs but if you want to look in the future etc. this is not so usefull

**Comment by Kinkelin** [comment]
Just comment out your debug code before you commit your bot to the challenge.

**Comment by natebursch** [comment]
I find that having my debug code is useful, but if it increasing the brain capacity, I can't get an accurate brain capacity unless I go through the tedious process of commenting every line out.... Sure not super annoying, but If I have to do it on every iteration it gets annoying.

**Comment by ZEvanderKarl** [comment]
That's a good point. When you're contending with the character limit, using Console.Writeline() will bloat the number, especially seeing as every character in a string is counted as a token.

**Comment by lucasmeneghin** [comment]
You code change the token counter yourself to ignore console.writeline instructions

**Comment by NiekvD** [comment]
most ide's have debugging tools integrated

**Comment by Firestorm-253** [comment]
You don't need debugs when commiting. Follow his advice.

> Just comment out your debug code before you commit your bot to the challenge.

**Comment by gamma-delta** [comment]
You can go `using C = Console.Out.Writeline;` at the top of your program.

**Comment by dudecon** [comment]
If you are using an IDE, it is much more convenient and powerful to use debug mode and breakpoints. This will allow you to introspect all variable states, step through execution, etc. It also has the advantage that breakpoints and debug readouts don't end up in your code, so you don't have to clean it up when you're done.

**Comment by gamma-delta** [comment]
> You can go `using C = Console.Out.Writeline;` at the top of your program.

Whoooops that's incredibly not correct. I'm not sure if there's a way to name the type of that function cause it has so many overloads. Yeah I'd just comment things out.

(I'm not using an IDE, fwiw.)

**Comment by gamma-delta** [comment]
Augh. i should actually figure out what I'm doing *before* I do it. *sigh.*

Put `Action<String> Print = Console.Out.WriteLine;` at the top of your file, right inside the class declaration.

Then instead of `Console.Out.WriteLine("Score of {0} is {1}", move, score)`, you can do `Print($"Score of {move} is {score}")`. Note the `$` before the string in the second one.

**Comment by Ayane** [comment]
You just need to use
```
#if DEBUG
        Console.WriteLine("Debug test");
#endif
```

All the code in the preprocessor DEBUG doesn't count but are correctly executed when you launch in debug mode.
It should not be necessary to remove them in the posted code, but the code need to be tested in release mode to be safe.
