### ISSUE TITLE
Animations cancel when another move is made too quickly

### ISSUE THREAD

**Issue by BeefyAndTheDucks** [SebLague/Chess-Challenge#168]
I have my bot make a move, but it's animation quickly gets cancelled when EvilBot is too fast to make its move.
Basically there should be a possibility for multiple animations to be playing at the same time.

**Comment by SebLague** [comment]
This is by design. If it bothers you, I suggest setting the MinMoveDelay value in the Settings class to something like 0.1f;

**Comment by BeefyAndTheDucks** [comment]
Ah okay! Thanks for pointing it out!
