### ISSUE TITLE
Spontaneously crashes when bot is still thinking after timeout

### ISSUE THREAD

**Issue by Jonah-Development** [SebLague/Chess-Challenge#171]
Sometimes (quite rarely, maybe 1 every 20 timeouts), when the bot has zero milliseconds left but is still thinking, the program will throw an exception and close/crash the window.
It seems like a problem with the board object.

It rarely happens. However, it is annoying when two versions of a bot play each other, and you lose the score when the window closes.
Does anyone else have this problem?

```console
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ChessChallenge.Chess.Board.MovePiece(Int32 piece, Int32 startSquare, Int32 targetSquare) in ...\Chess-Challenge\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 111
   at ChessChallenge.Chess.Board.MakeMove(Move move, Boolean inSearch) in ...\Chess-Challenge\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 125
   at ChessChallenge.Application.ChallengeController.PlayMove(Move move) in ....\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 266
   at ChessChallenge.Application.ChallengeController.Update() in ...\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 374
   at ChessChallenge.Application.Program.Main() in ...\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\Program.cs:line 40

---
Chess-Challenge.exe (process 38720) exited with code -1073741819.
```

**Comment by TheSecurityDev** [comment]
I'm getting this happening randomly too.

**Comment by FrederoxDev** [comment]
I've been experiencing this crash as well, it happens fairly often (around 1 in 20 as in original comment) to me when fighting bots

**Comment by FrederoxDev** [comment]
This issue can be fairly easily replicated by setting the time to 1 second, and having a bot which thinks for over that time

**Comment by TheSecurityDev** [comment]
> This issue can be fairly easily replicated by setting the time to 1 second, and having a bot which thinks for over that time
> 
> GetBotMove() in ChallengeController.cs
> ```
> API.Timer timer = new(PlayerToMove.TimeRemainingMs);
> API.Move move = PlayerToMove.Bot.Think(botBoard, timer);
> return new Move(move.RawValue); // <-- Returning value *without* checking if the game has already ended
> ```

So can we fix this by checking if the time has expired before returning the move in the think function?

**Comment by FrederoxDev** [comment]
> > This issue can be fairly easily replicated by setting the time to 1 second, and having a bot which thinks for over that time
> > 
> > GetBotMove() in ChallengeController.cs
> > ```
> > API.Timer timer = new(PlayerToMove.TimeRemainingMs);
> > API.Move move = PlayerToMove.Bot.Think(botBoard, timer);
> > return new Move(move.RawValue); // <-- Returning value *without* checking if the game has already ended
> > ```
> 
> So can we fix this by checking if the time has expired before returning the move in the think function?

I don't know if in that function is good, if for example it returns NullMove that causes the next round to end due to an illegal move

It'd probably be better to look where it's used

**Comment by SebLague** [comment]
Hi, thanks for bringing this to my attention. I've just pushed a patch which I believe fixes the issue. Please reopen if it happens again after updating.
