### ISSUE TITLE
You must install or update .NET to run this application.

### ISSUE THREAD

**Issue by CadenLast** [SebLague/Chess-Challenge#173]
I've never used c# before but I tried using Rider since I've always used Intellij and PyCharm before and I'm also on a Mac which I am not very familiar with but when I try to run it it says

`
Users/lastcaden/RiderProjects/Chess-Challenge/Chess-Challenge/bin/Debug/net6.0/Chess-Challenge
You must install or update .NET to run this application.

App: /Users/lastcaden/RiderProjects/Chess-Challenge/Chess-Challenge/bin/Debug/net6.0/Chess-Challenge
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (arm64)
.NET location: /usr/local/share/dotnet

The following frameworks were found:
  7.0.9 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=arm64&rid=osx.13-arm64

Process finished with exit code 150.

`

<img width="838" alt="image" src="https://github.com/SebLague/Chess-Challenge/assets/59887106/74b323c7-a222-4af4-bb59-c062393805ab">

I've tried adding it to the path like microsoft.com says and also tried adding it a different way since supposedly the internet says this is where it downloads.
<img width="316" alt="image" src="https://github.com/SebLague/Chess-Challenge/assets/59887106/2af9720c-252f-49ed-a4bd-e3086e90f047">

I'm not sure if I actually see it at that path though but that might just be me not understanding Macs. I can still run the dotnet command in the project path and it recognizes it but It won't run when I try to run it. Does anybody know anything else to try?

<img width="325" alt="image" src="https://github.com/SebLague/Chess-Challenge/assets/59887106/3fda4a07-83f8-48f1-ad72-1c37ecc589b2">

**Comment by austin-owensby** [comment]
Do you have .NET6 installed instead of just .NET7?

**Comment by CadenLast** [comment]
> Do you have .NET6 installed instead of just .NET7?

Ah yea that fixed it. Rider just automatically installed the latest version and I didn't think too much about it. Thank You.
