### ISSUE TITLE
Please select a valid startup item

### ISSUE THREAD

**Issue by Lu4nAlmeida** [SebLague/Chess-Challenge#174]
I downloaded the zip, extracted, and when I tried runnig it initially I got the "Can't find Chess-Challenge.dll" error, and  some other person said they got the same error because they were using Visual Studio 2019 but for the 2022 it worked, so I installed Visual Studio 2022 but now when I try running the bot code I get this error "Please select a valid startup item" and I'm not sure what this means (I'm new to Visual Studio).

**Comment by austin-owensby** [comment]
Did you open the `.sln` file in Visual Studio instead of opening a specific .cs file or folder?

**Comment by Lu4nAlmeida** [comment]
> Did you open the `.sln` file in Visual Studio instead of opening a specific .cs file or folder?

Yes, but when I do that it just brings a blank page and there are no other files in the right side to access or edit, it's really weird I don't know how to explain

**Comment by austin-owensby** [comment]
Do you have a screenshot?

**Comment by Lu4nAlmeida** [comment]
@

> Do you have a screenshot?

I have no idea how, I have no idea why, but I went to sleep and now when I woke up it just works, thanks for the willingness to help anyway.
