### ISSUE TITLE
Bug in move generator

### ISSUE THREAD

**Issue by eduherminio** [SebLague/Chess-Challenge#189]
In position `r1bqkbnr/pppppppp/n7/8/2B5/4P3/PPPP1PPP/RNBQK1NR b KQkq - 2 2` no legal moves are generated for black.

Debugging it, `currMoveIndex` fails to get incremented in [these 3 lines](https://github.com/SebLague/Chess-Challenge/blob/96cdff5d2407d0f069ac58ba12b1c56066499833/Chess-Challenge/src/Framework/Application/Helpers/API%20Helpers/APIMoveGen.cs#L70-L72), so no moves are returned.

**Comment by harrisi** [comment]
I set that to be the starting FEN for every game and I'm having moves be generated just fine. Are you sure your bot isn't doing something else that changes available moves?

**Comment by eduherminio** [comment]
I double checked and you're right, it's not happening by just setting that position.
So it's probably related with some of the open bugs regarding `UndoMove`.
