### ISSUE TITLE
Is there any time limit to generate issue a valid move?

### ISSUE THREAD

**Issue by IvanovCosmin** [SebLague/Chess-Challenge#194]
If there is, it should be added in the requirements.

**Comment by harrisi** [comment]
There is no limit per move, but each player only has 60 seconds per game. So, technically, the time limit to generate a valid move is 60 seconds.

**Comment by mcthouacbb** [comment]
In IChessBot.Think(), there's a second parameter called "timer". The timer has a property called "MillisecondsRemaining" which tells you how much time you have left on the clock. If your clock runs down to 0 then you lose. It also has a property called "MillisecondsElapsedThisTurn" so you can keep track of time while thinking if needed.

**Comment by SebLague** [comment]
Yes, the answers here are correct. You can find this line in the rules:
If your bot makes an illegal move or runs out of time, it will lose the game.
Games are played with 1 minute per side by default (this can be changed in the settings class). The final tournament time control is TBD, so your bot should not assume a particular time control, and instead respect the amount of time left on the timer (given in the Think function).
