### ISSUE TITLE
GetAllPieceLists() doesn't update after board.MakeMove()

### ISSUE THREAD

**Issue by Basinity** [SebLague/Chess-Challenge#207]
```
foreach (Move[] move in board.GetLegalMoves())
{
    PieceList[] oldPieceList = board.GetAllPieceLists();
    board.MakeMove(move);
    if (oldPieceList == board.GetAllPieceLists() && move.IsCapture)
        Console.WriteLine("PieceList is the same after capture!");
    board.UndoMove(move);
}
```

The PieceList Array doesn't update after making a move with board.MakeMove().
This might be intended to only receive the PieceLists of the current board that is being played?

**Comment by Francobdq** [comment]
Hello! I had the same problem and it was solved by pulling the new version. Be sure to check the .readme FAQ frequently as it is being updated quite often

**Comment by Basinity** [comment]
Hey, I am using the latest version (1.12) and have read the FAQ. The problem which was mentioned in the FAQ refers to the GetPieceList function. I am talking about the GetAllPieceLists function.

**Comment by Francobdq** [comment]
Keep in mind that GetAllPieceLists returns a list of lists. It will look something like this:
[
[whitepawn1, whitepawn2, ...],
[whiteknight1, whiteknight2, ...],
...,
[blackking1]
]

With a total of 12 constant elements (representing 12 unique pieces). If you remove a white pawn, you will still have the same number of elements. To achieve what you want, you need to iterate within the second list. You could do it like this:
`
foreach (Move[] move in board.GetLegalMoves())
{
    board.MakeMove(move);
    foreach (PieceList pieceList in board.GetAllPieceLists())
        {
            foreach (Piece piece in pieceList)
            {
                // here your code to do something with the piece
            }
        }
    board.UndoMove(move);
}
`

**Comment by Basinity** [comment]
I have noticed when comparing things like `oldPieceList == board.GetAllPieceLists()` it would still output true, even though some properties might have changed further inside of them. I never actually had a problem. Thanks @Francobdq
