### ISSUE TITLE
SquareIsAttackedByOpponent is not switching sides after TrySkipTurn

### ISSUE THREAD

**Issue by LukasCaha** [SebLague/Chess-Challenge#208]
Desired behavior: test if my bot attacks square.

Original approach: TrySkipTurn to switch sides; test if the square is attacked by opponent (= my bot)

Workaround: use MakeMove, however this is not 100% accurate

Is it possible TrySkipTurn is not changing the cache used to calculate SquareIsAttackedByOpponent?

**Comment by draeg82** [comment]
Isn't that the purpose of Move.NullMove?  MakeMove(Move.NullMove)?

**Comment by ernestoyaquello** [comment]
I am experiencing the same thing:

```csharp
board.ForceSkipTurn();
var isAttacked = board.SquareIsAttackedByOpponent(square); // returns true
board.UndoSkipTurn();
board.SquareIsAttackedByOpponent(square); // still returns true
```

**Comment by SebLague** [comment]
Hi, sorry for the slow response! I unfortunately haven't been able to reproduce this issue. Here's a simple test that gives the correct result, are you able to give a counterexample?

```
using ChessChallenge.API;
using System;

public class MyBot : IChessBot
{
    public Move Think(Board board, Timer timer)
    {
        Board testBoard = Board.CreateBoardFromFEN("3k2q1/8/8/8/8/3K4/8/8 w - - 0 1");
        // White to move in current position, opponent is black.
        bool blackAttacksG1 = testBoard.SquareIsAttackedByOpponent(new Square("g1"));
        Console.WriteLine("Opponent (black) attacks g1: " + blackAttacksG1 + " (should be true)");
        // Skip turn
        testBoard.ForceSkipTurn();
        // Black to move in current position, opponent is white.
        bool whiteAttacksG1 = testBoard.SquareIsAttackedByOpponent(new Square("g1"));
        Console.WriteLine("Opponent (white) attacks g1: " + whiteAttacksG1 + " (should be false)");

        // Return anything
        return board.GetLegalMoves()[0];
    }
}

```

**Comment by ernestoyaquello** [comment]
Never mind, this was a very basic comprehension problem on my part, turns out it was too late to think clearly. 🤦 

Sorry about that, and thanks for the quick response!

**Comment by ernestoyaquello** [comment]
However, there seems to be a problem with `SquareIsAttackedByOpponent`, which I think is what confused me in the first place.

When I run this:

```cs
using ChessChallenge.API;
using System;

public class MyBot : IChessBot
{
    public Move Think(Board board, Timer timer)
    {
        Board testBoard = Board.CreateBoardFromFEN("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1");

        // Make a few initial moves, no pieces is under attack yet
        testBoard.MakeMove(new Move("g1f3", board));
        testBoard.MakeMove(new Move("b8c6", board));
        testBoard.MakeMove(new Move("b1c3", board));

        // Somehow the white bishop at c1 appears to be under attack?
        Console.WriteLine("Is c1 attacked? " + testBoard.SquareIsAttackedByOpponent(new Square("c1")));
        Console.WriteLine();
        Console.WriteLine(testBoard.ToHumanReadableString());

        // Return anything
        return board.GetLegalMoves()[0];
    }
}
```

This is the output I get:

```
Is c1 attacked? True

+---+---+---+---+---+---+---+---+
| r |   | b | q | k | b | n | r | 8
+---+---+---+---+---+---+---+---+
| p | p | p | p | p | p | p | p | 7
+---+---+---+---+---+---+---+---+
|   |   | n |   |   |   |   |   | 6
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   | 5
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   | 4
+---+---+---+---+---+---+---+---+
|   |   | N |   |   | N |   |   | 3
+---+---+---+---+---+---+---+---+
| P | P | P | P | P | P | P | P | 2
+---+---+---+---+---+---+---+---+
| R |   | B | Q | K | B |   | R | 1
+---+---+---+---+---+---+---+---+
  a   b   c   d   e   f   g   h
```

But unless I am massively misunderstanding something (maybe I am?), c1 is not under attack?

**Comment by SebLague** [comment]
Hey, I totally understand your confusion -- I probably could have named that function better!
What's happening here is that after the move b1c3, it is now black's turn on the board. This means that the 'opponent' is white (opponent here just means the player who isn't on move, it has nothing to do with which side your bot is playing). So what you're asking is whether white 'attacks' the c1 square, which it does with both the rook and the queen. (maybe controls would have been a better term?).

Anyway, I hope that makes sense! I can't change the function name now, but let me know if you think there's a way I could phrase this more clearly in the documentation.

**Comment by ernestoyaquello** [comment]
Hmm, I see what you mean, it all makes sense then. In fact, now that I read the documentation again, I am not sure it could be explained any better! You cannot make the documentation totally idiot-proof, some of us are just too at misreading! 😄

This is totally clear to me now, thanks a lot for the explanation!

**Comment by SebLague** [comment]
Great, happy to hear it makes sense now! :)
