### ISSUE TITLE
List<Type> is 3 more tokens than var, and Type[] is 2 more tokens than var

### ISSUE THREAD

**Issue by Squaduck** [SebLague/Chess-Challenge#209]
The title speaks for itself.
I don't know if there are any good ways to fix this. 
Maybe "List", '<', '>', '[', and ']' could be excluded from counting?

**Comment by jgh07** [comment]
Just use `var` then?

**Comment by SebLague** [comment]
Ideally the token counter would count these as the same, but I'd prefer not to change it now.
