### ISSUE TITLE
Running base program with dotnet returns an error about raylib and does not run.

### ISSUE THREAD

**Issue by carsonetb** [SebLague/Chess-Challenge#211]
I'm on Linux and I just installed the .NET libraries to try to do this competition. Being on Linux, I couldn't install Visual Studio so I just had to use vscode. I built and ran the program with dotnet, but it failed to run and printed this error:

`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'raylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libraylib: cannot open shared object file: No such file or directory
   at Raylib_cs.Raylib.SetTraceLogCallback(IntPtr callback)
   at ChessChallenge.Application.Program.Main() in /home/cbates/Chess-Challenge/Chess-Challenge/src/Framework/Application/Core/Program.cs:line 23`

Thanks for the help!

**Comment by carsonetb** [comment]
Actually I fixed it, what I did is manually built raylib from [https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux](url) (I followed the section titled Build raylib using CMake), moved EVERY file ending in .so (in my case it was libraylib.so which was linked to libraylib.so.450 which was linked to libraylib.so.4.5.0 which actually had the module in it) into the Chess-Challenge/bin/Debug/.net6.0 directory. After that the program ran fine! Hopefully this helps anyone on Linux without Visual Studio who's encountering this bug.

**Comment by phantom-balance** [comment]
where was the librarylib.so file located?

**Comment by phantom-balance** [comment]
Could you give a more detailed description on how to fix this issue, i am facing this issue and can't solve it.

**Comment by JonAlexandra** [comment]
> where was the librarylib.so file located?

They are located in build/raylib. If you do not see them, you probably haven't completed they cmake build process. Quoting from the cmake section of the website: 

git clone https://github.com/raysan5/raylib.git raylib
cd raylib
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make
sudo make install

**Comment by JonAlexandra** [comment]
> Actually I fixed it, what I did is manually built raylib from [https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux](url) (I followed the section titled Build raylib using CMake), moved EVERY file ending in .so (in my case it was libraylib.so which was linked to libraylib.so.450 which was linked to libraylib.so.4.5.0 which actually had the module in it) into the Chess-Challenge/bin/Debug/.net6.0 directory. After that the program ran fine! Hopefully this helps anyone on Linux without Visual Studio who's encountering this bug.

Thanks a lot. I had the same issue, but this worked for me as well.

**Comment by carsonetb** [comment]
> > Actually I fixed it, what I did is manually built raylib from [https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux](url) (I followed the section titled Build raylib using CMake), moved EVERY file ending in .so (in my case it was libraylib.so which was linked to libraylib.so.450 which was linked to libraylib.so.4.5.0 which actually had the module in it) into the Chess-Challenge/bin/Debug/.net6.0 directory. After that the program ran fine! Hopefully this helps anyone on Linux without Visual Studio who's encountering this bug.

No problem, I'm glad I could help. Apologies for not saying where the libraylib.so files were located. Another comment already answered, but I got them from /usr/local/lib, as instructed by one of the comments in the Linux build and run instructions, ([https://github.com/SebLague/Chess-Challenge/discussions/3#discussioncomment-6516407](url)). Now I feel better that other people had the same issues as me, and I wasn't making a simple mistake.
