### ISSUE TITLE
board.SquareIsAttackedByOpponent might be broken

### ISSUE THREAD

**Issue by penguinsrepic** [SebLague/Chess-Challenge#214]
Something I noticed while trying to shrink my code is that for some reason
`board.MakeMove(move);
        Move[] enemyLegalMoves = board.GetLegalMoves(true);
        foreach (Move enemyMove in enemyLegalMoves)
        {
            if (enemyMove.TargetSquare == move.TargetSquare)
            {
                value -= pieceValues[(int)move.MovePieceType];
                break;
            }
        }
        board.UndoMove(move);`

makes my bot perform better (from mostly losing to winning nearly 50% of games) than

`board.MakeMove(move);
        if (board.SquareIsAttackedByOpponent(move.TargetSquare)) value -= pieceValues[(int)move.MovePieceType];
        board.UndoMove(move);`

even though I think they should have the same function.

**Comment by StevenChristy** [comment]
Once you've made your move with MakeMove, the opponent is now you. If you want to know if you will be targeted after making this move, then you need to see if one of the legal moves of your opponent as you did in the first case.

**Comment by StevenChristy** [comment]
I thought I might add a tip. Recapturing your piece isn't the worst thing that could result from a move. Your move may have exposed an attack on your queen or a checkmate. What you need to do after making your move is to see what the opponents best reply is. If the best reply is capturing your queen, then clearly you don't gain a free pawn or whatever it was the move would have gained you. So essentially for each move you make calculate what you gain from the move, then calculate what the opponents best response is as a loss. When losses exceed gains consider a different move.

**Comment by BronsonCarder** [comment]
Wait... I'm sorry, this is slightly tangential. But, is that how that works?

So, like, if I were to "board.MakeMove" and then "GetLegalMoves" the moves I would get would be the opponents?
...I spent the last, like, hour and a half writing a function which had to go through PieceList[], then PieceList, then Piece, then Square just to get the squares that the opponent can legally attack after my move. 
I'm also a total noob and figuring out a lot of this stuff as I go. lmao
