### ISSUE TITLE
How will the 256mb limit be measured?

### ISSUE THREAD

**Issue by Bulmenisaurus** [SebLague/Chess-Challenge#216]
According to the readme,
> Your bot may not allocate more than 256mb of memory

The problem is, when launching the GUI with the simple bot (that returns the first legal move), according to Visual Studio 149 MB is used
![image](https://github.com/SebLague/Chess-Challenge/assets/63682890/d194e171-e097-46f5-b3d8-63bd4b94470f)

Will this 149 mb be counted as part of the 256mb limit? Or do we need to test our bots memory usage a different way?

**Comment by Odin7094** [comment]
Mine goes up to 136MBs while being quite light. I assume max allowed would be calculated like memory of program with empty mybot + 256 MB. Either way you get somewhere between 120-256MB.

**Comment by BeefyAndTheDucks** [comment]
I hit take a snapshot in the overview, then I selected it and found my class. Not sure if it is accurate though, but that is what I went with.

**Comment by SebLague** [comment]
No those 194 MBs will not be included. It also doesn't include memory allocated when generating moves. You only really need to worry about this if you are creating gigantic look up tables (such as a transposition table for instance). I'll update the rules to try make this clearer.
