### ISSUE TITLE
How long will the games in the tournment be

### ISSUE THREAD

**Issue by NiekvD** [SebLague/Chess-Challenge#219]
it the rules it is a bit unclear, so i just want to make sure how long it is

**Comment by HanssenJarrah** [comment]
> Games are played with 1 minute per side by default (this can be changed in the settings class). The final tournament time control is TBD, so your bot should not assume a particular time control, and instead respect the amount of time left on the timer (given in the Think function).

**Comment by SebLague** [comment]
Hi, I'm sorry I can't say exactly how long the tournament games will be as it depends on the number of entries I end up receiving.
