### ISSUE TITLE
Chess-Challenge.exe not found

### ISSUE THREAD

**Issue by Magnus24112** [SebLague/Chess-Challenge#22]
I have .NET 6.0 installed but I can't build

![image](https://github.com/SebLague/Chess-Challenge/assets/56786591/29226fef-1908-431b-a9b7-2be210550eda)

**Comment by CREAsTIVE** [comment]
try 
![image](https://github.com/SebLague/Chess-Challenge/assets/62616308/9c55c414-3dce-4fc4-ac3c-b845750a364f)

**Comment by Magnus24112** [comment]
> 

Where do I find that?

**Comment by Magnus24112** [comment]
I only see this
![image](https://github.com/SebLague/Chess-Challenge/assets/56786591/a8dde4b2-4785-4e37-9922-46c1ea11bccc)

**Comment by CREAsTIVE** [comment]
Oh, you need to open youre project as PROJECT, not a folder. Close VS and double-click Chess-Challenge.sln (or open through VS)
