### ISSUE TITLE
MovePiece() causes an error despite never being called for. (SOLVED)don't make a global Move

### ISSUE THREAD

**Issue by Moonwalker316** [SebLague/Chess-Challenge#221]
It gives a null reference exception despite never being called. THis occurs after I play the first move agianst my bot.

**Comment by CaptainDeathead** [comment]
Update to latest version of the repo 😁

**Comment by ryanheath** [comment]
Can you post the stacktrace of the exception?

**Comment by CoolJWB** [comment]
@Moonwalker316 if it's solved please press the close issue button at the bottom part of the page!

**Comment by SebLague** [comment]
Closing since solved
