### ISSUE TITLE
Still possible to add more code

### ISSUE THREAD

**Issue by noelhug** [SebLague/Chess-Challenge#224]
Heyya, sorry for making another complications to the rules 😅.

But it is still possible to reduce the size of the program (I think, haven't tested it that much :).
It is possible to do it by converting the program to hex (https://gchq.github.io/CyberChef/#recipe=To_Base64('A-Za-z0-9%2B/%3D')To_Hex('Space',0)&input=TW92ZVtdIG1vdmVzID0gYm9hcmQuR2V0TGVnYWxNb3Zlcygp).

Then, take as many of the hex chars and put them in a hex number (can be at most 16 hex digits) -> which then can be converted back to arbitrary strings:

ulong[] hexNumbers = new ulong[]
{
    0x545739325a567464, 0x49473176646d567a,
};

List<byte> hexBytesList = new List<byte>();

foreach (ulong hexNumber in hexNumbers)
{
    byte[] bytes = BitConverter.GetBytes(hexNumber);
    if (BitConverter.IsLittleEndian)
        Array.Reverse(bytes); // ensures bytes are in the correct order
    hexBytesList.AddRange(bytes);
}

byte[] hexBytes = hexBytesList.ToArray();

string ascii = Encoding.ASCII.GetString(hexBytes);

byte[] data = Convert.FromBase64String(ascii);
string decodedString = Encoding.UTF8.GetString(data);

Console.WriteLine(decodedString);
       
I don't see any good way to change the Token counter to prevent this.

**Comment by SebLague** [comment]
Hi, this is allowed :)
