### ISSUE TITLE
board.GetPiece not working properly.

### ISSUE THREAD

**Issue by Gourab-Ghosh** [SebLague/Chess-Challenge#229]
board.GetPiece showing Null on square d5 in position rnbqkbnr/ppp1pppp/8/3p4/4P3/5P2/PPPP2PP/RNBQKBNR b KQkq - 2 2

The order in which I made the moves is e2e4 d7d5 f2f3

**Comment by jvrst** [comment]
Are you running the latest version as per the [FAQ](https://github.com/SebLague/Chess-Challenge#faq-and-troubleshooting)?

```
GetPiece() function is giving a null piece after making a move

    Please make sure you are using the latest version of the project, there was a bug with this function in the original version
```

**Comment by SebLague** [comment]
This sounds like the bug I had to fix in the original version, sorry about that! Closing this, but please reopen of course if the problem persists after updating to the latest version.
