### ISSUE TITLE
Unable to resolve Raylib-cs dep using Rider IDE 

### ISSUE THREAD

**Issue by tomgelu** [SebLague/Chess-Challenge#23]
I tried to install it through the dotnet cli but it says that no version 4.5.0.2 of Raylib-cs matches net6.0: 

`Chess-Challenge.csproj: [NU1100] Unable to resolve 'Raylib-cs (>= 4.5.0.2)' for 'net6.0'.`

**Comment by CREAsTIVE** [comment]
Try install it from nuget
![image](https://github.com/SebLague/Chess-Challenge/assets/62616308/feb31b79-c341-46c8-876a-672d537d0fdc)

![image](https://github.com/SebLague/Chess-Challenge/assets/62616308/e8502a51-c4a4-492f-86a6-6a77ab4e565e)

**Comment by tomgelu** [comment]
It was a permission problem with NuGet, I had to delete NuGet.Config and restart Rider.
