### ISSUE TITLE
warning in the board class for standard value null

### ISSUE THREAD

**Issue by jonigrin** [SebLague/Chess-Challenge#232]
I started programming my bot, after one of the versions I built and it said that there is an error on the board class because the default value for source is null, I ignored it because who cares about errors and ran the program, after the first human move it crashed, I didn't touch any file other than MyBot.cs

**Comment by jonigrin** [comment]
ok, I found a bug in my code, I fixed it, now the program doesn't crash, but the warning still exists

**Comment by SebLague** [comment]
I've just uploaded a patch that removes the warning
