### ISSUE TITLE
Is the timer deterministic based on code length or does it completely rely on how fast your hardware is?

### ISSUE THREAD

**Issue by loki12241224** [SebLague/Chess-Challenge#238]

**Comment by penguinsrepic** [comment]
The timer is real time. I'm not sure I understand your question.

**Comment by hypnotox** [comment]
It's just delta time, so completely up to how optimised your code and how fast your hardware is. Since it will probably all be ran on the same hardware, which I'm guessing will be quite powerful, there shouldn't be an issue.

**Comment by loki12241224** [comment]
> It's just delta time, so completely up to how optimised your code and how fast your hardware is. Since it will probably all be ran on the same hardware, which I'm guessing will be quite powerful, there shouldn't be an issue.

alright that makes sense. i was mainly just wondering if the time per move was purely based on how much code was ran before a move was determined.
