### ISSUE TITLE
I get this error when i start a game

### ISSUE THREAD

**Issue by MohammedGamer85** [SebLague/Chess-Challenge#240]
![image](https://github.com/SebLague/Chess-Challenge/assets/100155245/89ffec28-1a17-442b-81de-e2b4e639b46c)

**Comment by MohammedGamer85** [comment]
i just downloaded it so i am very sure i am on the latest version

**Comment by penguinsrepic** [comment]
If you're using Visual Studio and you click continue again the chess application terminal will show what line of your program caused the issue. I think when I got that error it was usually from undoing a move wrong or something like that.

**Comment by MohammedGamer85** [comment]
Fixed it i had miss placed my undo move functions
