### ISSUE TITLE
Constant time limit in rules, but time dependent on system

### ISSUE THREAD

**Issue by marc7s** [SebLague/Chess-Challenge#242]
In the rules, it is specified:

> If you have added a constructor to MyBot (for generating look up tables, etc.) it may not take longer than 5 seconds to complete.

But according to #238, the timer is based on real time. So if my system would perform better than the system the submissions will be tested on, then my submission could possibly be ruled as illegal due to the constructor taking longer than 5 seconds on that machine, even though it was under 5 seconds on my machine when testing. Or am I understanding the rules incorrectly?

**Comment by convenient-username** [comment]
You're understanding it correctly as far as I can tell, so be careful. The machine that will do the judging will no doubt be powerful though, so I don't see the difference being that large.

**Comment by marc7s** [comment]
Well in that case it feels unfair. You have no way of knowing exactly how close to the limit you are, which I don't think is good enough for a rule. If the setup time is the limiting factor for your bot, you would like to spend as much time on it as possible. But since you don't know if your 4.5 second setup is infact 5.2 or 3 seconds, you are either missing out on performance or will be disqualified with no way of knowing for sure. 

I just think the rules should be clear and allow you to confidently know if you are braking them, or leaving performance on the table by being overly careful.

**Comment by EikeSchwass** [comment]
You could measure the time spend in your constructor yourself and if you get close to 5 seconds stop your setup routine.

**Comment by Pds314** [comment]
> 

Do we actually have a way to measure time ourselves given the tools available?

**Comment by EikeSchwass** [comment]
```
var start = DateTimeOffset.Now;
while((DateTimeOffset.Now-start).TotalMilliseconds<4500)
{
    // Setup
}
```

**Comment by Pds314** [comment]
Oh nice. I found my own workaround which is that we actually have access to Timer which has an internal stopwatch.

**Comment by jonigrin** [comment]
@marc7s can be closed now?

**Comment by marc7s** [comment]
The main question whether the rules will be clarified, or if you are meant to spend tokens to account for this with some timer like suggested still remains, but as it does not seem like this will get answered I'll close it anyway
