### ISSUE TITLE
Running on ubuntu; issues with raylib

### ISSUE THREAD

**Issue by phantom-balance** [SebLague/Chess-Challenge#243]
`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'raylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libraylib: cannot open shared object file: No such file or directory
   at Raylib_cs.Raylib.SetTraceLogCallback(IntPtr callback)
   at ChessChallenge.Application.Program.Main() in /home/phantom/Chess-Challenge/Chess-Challenge/src/Framework/Application/Core/Program.cs:line 23`

This error message pops up, a closed issue on the same problem does exist but it's very unclear as to how they solved their issue. Can anyone help me fix this.

**Comment by michaelb18** [comment]
For ubuntu, you need to download raylib and build it from source(at least this is what I did and it worked)

1. sudo apt install build-essential git
2. sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
3. git clone https://github.com/raysan5/raylib.git raylib
4. cd raylib/src/
5. make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED
6. sudo make install RAYLIB_LIBTYPE=SHARED
7. cp /usr/local/libraylib.so bin/Debug/net6.0/

**Comment by phantom-balance** [comment]
Thank your so much, work for me after the 6th step. didn't have to copy and paste the librarylib.so file elsewhere.

**Comment by phantom-balance** [comment]
The program does run but whenever I run the file using `dotnet run` the changes made to the code base in `MyBot.cs` dissapears.
