### ISSUE TITLE
The type or namespace Evilbot could not be found (Resolved)

### ISSUE THREAD

**Issue by BronsonCarder** [SebLague/Chess-Challenge#245]
Last night, I left a battery of tests running, wanted to get th
rough the full 1000. 
Ran fine, no issues (I did pretty good, 46 losses, 86 draws). 

But... now the project won't recognize Evilbot.
I asked my friendly neighborhood discord community, they suggested an issue with "chess-challenge.csproj" where it compiles Evilbot, but that was normal.
I restarted the program, I even pasted back in the full original Evilbot code. 

I'm sure I could just re-download the project file and paste back in my bot. But, this seemed like it could be a pretty major issue, so I thought I'd report it. 

I'm thinking it has something to do with VisualStudio being way too overzealous with it's automatic refactoring... It keeps adding "using ChessChallenge.Chess" and then it gets confused about which definitions to use. That's by far the most common one.

**Comment by BronsonCarder** [comment]
After a bit of experimentation, I was able to recreate the issue:

Upon changing Evilbot to some code shared in the discord, visual studio tried to add "using ChessChallenge.Example" to ChallengeController.cs.
It's telling me that the type or namespace "Example" does not exist in that namespace. So, I figured I'd just delete that line, it probably just added a lib that I don't need, right?
Well, removing that line causes the "Evilbot could not be found" error.

**Comment by mcthouacbb** [comment]
EvilBot has to be in the "ChessChallenge.Example" namespace. You might've accidently deleted that namespace when pasting a MyBot class since MyBot doesn't reside in a namespace.

**Comment by BronsonCarder** [comment]
Oh... Huh, I've pasted in a bunch of people's code without adding that namespace, and it's worked fine. 
Ok, I'll look out for that in the future, thank you!

**Comment by BronsonCarder** [comment]
Idk, I guess I'm still confused about this. 

I just re-downloaded the code, started entirely over.
I posted in someone else's bot from the discord. 

All I had to do was change mybot to evilbot. 
Trying to add "namespace ChessChallenge.Example" gives me an error that says namespace example doesn't exist.

**Comment by BronsonCarder** [comment]
Ok, I tried to run it an it errored out, saying that example doesn't exist in the context of the challenge controller.
And now when I add the namespace ChessChallenge.Example to evilbot, that error goes away, but we're back to:
The type or namespace Evilbot could not be found.

**Comment by BronsonCarder** [comment]
Gorrammit... I'm sorry for the waste of time...
I had it as "Evilbot."
Not "EvilBot."
LMFAO
