### ISSUE TITLE
Raylib texture loading issue

### ISSUE THREAD

**Issue by crp222** [SebLague/Chess-Challenge#247]
` piecesTexture = Raylib.LoadTexture(UIHelper.GetResourcePath("Pieces.png"));`  this line in BoardUI ( line 56 ) doesn't load the texture for me.
A check like this 
`  
Console.WriteLine("Piece.png loading...");
while (!Raylib.IsTextureReady(piecesTexture)){}
`  
seems like just wont stop ever. 

I have amd rx550.

I tried methods like : ` Raylib.LoadImageFromMemory();` and then use the image, but i couldn't  load an image either, the image height always remained 0.

Anyone else had problem with this?

**Comment by SebLague** [comment]
This issue seems to occur when the path to the project contains letters with diacritics. Would you mind posting the path to your project or confirming if it has any non-ascii characters? Currently looking into a solution

**Comment by crp222** [comment]
The path was the issue, thank you. Should I close this then?

**Comment by SebLague** [comment]
You can keep it open, I'll close it if I find a proper solution

**Comment by R0b3rt1337** [comment]
I suspect this is either an issue with [`Path.Combine`](https://learn.microsoft.com/en-us/dotnet/api/System.IO.Path.Combine?view=net-6.0) throwing an ArgumentException, or Raylib not being able to load from these kinds of paths. If you have time, could you check if the full path to your Pieces.png asset contains any characters returned by `Path.GetInvalidPathChars()`?

**Comment by crp222** [comment]
It's not the `Path.Combine` , i printed the path after combining and i got the right path. 
But the simple `File.ReadAllBytes()` works for me, and there is a `Raylib.LoadImageFromMemory()` function which 
two combined theoretically fix the issue, but i couldn't make it work, maybe someone smarter than me would try it?

Also put "á é ő ű ú  í ó" in your path to reproduce the bug.

**Comment by SebLague** [comment]
I've added a patch that seems to fix this, so closing for now. Note however that font (or possibly shader/both) is still not loading correctly for non-ascii path so I will continue to look into it.
