### ISSUE TITLE
[BUG] Zobrist key bug in make / unmake move

### ISSUE THREAD

**Issue by Jakur** [SebLague/Chess-Challenge#248]
Currently, zobrist keys are not correctly updated on make / unmake move. Particularly, they are bugged when a pawn is pushed two squares forward. This is an important issue because it will mar all attempts to use a transposition table. 

The following code demonstrates the bug, with an assertion that the zobrist key is identical before and after the make / unmake process. The assertion will pass when most moves are made, but immediately crash if the player plays a 2 square pawn push. 
```cs

using ChessChallenge.API;
using System.Collections.Generic;
using System.Diagnostics;


public class MyBot : IChessBot

{

    public Move Think(Board board, Timer timer)
    {
        SearchInfo info = new();
        System.Console.WriteLine("Starting search...");
        NegaMax(board, 1, info);
        Move mv = info.table.GetValueOrDefault(board.ZobristKey);
        return mv;
    }

    int NegaMax(Board board, int depth, SearchInfo info)
    {
        if (depth == 0) return evaluate(board);
        ulong parent_key = board.ZobristKey;
        int max = -1_000_000;
        foreach (var m in board.GetLegalMoves())
        {
            board.MakeMove(m);
            int score = -NegaMax(board, depth - 1, info);
            if (score > max)
            {
                info.table[parent_key] = m;
                max = score;
            }
            board.UndoMove(m);
            Trace.Assert(board.ZobristKey == parent_key);
        }
        return max;
    }

    int evaluate(Board board)
    {
        return 0;
    }
}

class SearchInfo
{
    public Dictionary<ulong, Move> table = new();
}
```

**Comment by Disservin** [comment]
I can confirm, however it's not limited to double pawn pushs. Cant say in which cases it happens, but rook moves, knight moves and bishop moves all fuck up the ZobristKey... which leads me to believe only single pawn pushs are done correctly.

I also advise you to prepend `[BUG]` to the title. Might be a bit easier for Seb to spot.

**Comment by SebLague** [comment]
This should be fixed in the latest patch. Thanks for letting me know, and apologies for the bug!
