### ISSUE TITLE
[BUG] Bot brain capacity: square brackets counted individually unlike round or curly brackets

### ISSUE THREAD

**Issue by RobotLazerShark** [SebLague/Chess-Challenge#256]
I was doing some tests to see what I would need to keep an eye on in respect to the capacity limitation, and noticed this bug.
While the (round brackets) and {curly brackets} are counted in pairs, the [square brackets] are counted individually when it comes to complexity.

This is what I tested:
```C#
private int _testVariable; // Capacity cost: 2
private int[] _testVariable; // Capacity cost: 4


private int _testVariable = 1; // Capacity cost: 4
private double _testVariable = (double)1; // Capacity cost: 6


private void Test() // Capacity cost: 5
{
    return;
}

private void Test() // Capacity cost: 6
{
    { }
    return;
}
```

**Comment by dudecon** [comment]
All three of the "close" closures are excluded from the syntax tree token counter in lines 18 to 20 of TokenCounter.cs
I have verified that these exclusions are having effect. The "double count" you are seeing is from an invisible "OmittedArraySizeExpression" token which is generated when you do not specify an array size on initialization.

If you are curious to see the full readout of all the tokens that are counted, uncomment line 44 in TokenCounter.cs and then add `using System;` to the imports at the top of the file.

**Comment by RobotLazerShark** [comment]
Ah, that's very interesting! Thanks for clarifying. I will definitely be using that debug tip once I start hitting the capacity limit.
