### ISSUE TITLE
System.Numerics allows BigInteger, which essentially enables infinite tokens

### ISSUE THREAD

**Issue by AndreVallestero** [SebLague/Chess-Challenge#26]
Essentially, you could store a 1MB weights file (or whatever binary data) into a BigInt using the following:
`var myBigInteger = new BigInteger(0x123456789ABCDEF123456789ABCDEF123456789ABCDEF123456789ABCDEF);`

**Comment by jsettlem** [comment]
That won't compile, integer literals can only be up to 64-bits. You would have to use a byte array or string to get an arbitrarily large bigint, which would use tokens.

**Comment by tamasgithub** [comment]
But if it compiles, can I use this approach? E.g. define a double 12345678.11112222 to store my 4 weights 12.34, 56.78, 11.11 and 22.22?

**Comment by SebLague** [comment]
Yes you can pack multiple weights into a single value however you want
