### ISSUE TITLE
UndoMove affecting copies of a board

### ISSUE THREAD

**Issue by Eldriitch** [SebLague/Chess-Challenge#262]
When using `MakeMove` and `UndoMove` I observed the following unusual behaviour with `UndoMove`.

<img width="604" alt="image" src="https://github.com/SebLague/Chess-Challenge/assets/49596061/b5e79c40-57fc-4452-8449-5d07a1688d8a">

To explain, `originalBoard` is the FEN string for the board before we do anything. Then, we make a move, and see the result in `afterMove`. Then, I create a new node in the search tree - and as part of that I include the data of the board (so this node can compute its legal moves and so on). The board, as it is stored in `newNode` is then displayed in `boardInNewNode`. Finally, on the original board, I call `UndoMove(move)`. The behaviour is then that the stored board in `newNode` *also* has the move undone, as is displayed in `afterUndo`. 

I'm new to C# so maybe I'm just not understanding something, but this certainly *feels* like a bug! My default expectation is certainly not that the board in `newNode` would be mutated alongside the original board (hence why it broke my bot). At very least, if this is the intended behaviour, it should be documented!

**Comment by R0b3rt1337** [comment]
Are you storing a new board instance in your node, or are you storing the existing board? It could be that you are storing a reference to the original Board and are modifying it instead.

**Comment by raphaelcastaneda** [comment]
This info might help you understand what's going on:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types

`Board` is a class, so instances of it are reference types. The behavior you're describing is expected in C#.
What you might do instead is store the FEN and use it to make a new instance, like `newBoard = Board(storedFEN)` when you need it.

**Comment by dudecon** [comment]
Specifically, you'll want to use the Board.CreateBoardFromFEN(string fen) function described in the documentation:
https://seblague.github.io/chess-coding-challenge/documentation/#board-class
Otherwise, you're creating a reference to the existing board object, which will update everywhere it is referenced, just like any other variable.

**Comment by QuinnCG** [comment]
> Specifically, you'll want to use the Board.CreateBoardFromFEN(string fen) function described in the documentation: https://seblague.github.io/chess-coding-challenge/documentation/#board-class Otherwise, you're creating a reference to the existing board object, which will update everywhere it is referenced, just like any other variable.

Board.CreateBoardFromFEN is labeled as slow so you'd need to be careful using it. You could call `board.MakeMove(move);` to simulate a move then call `board.TrySkipTurn()` if you want it to go back to the original side's turn then you can calculate whatever you want and call `board.UndoSkipTurn()` and `board.UndoMove(move)`.

The one caveat to this is that nesting multiple skip turns/make moves and then calling to undo them all can lead to some seemingly buggy behavior (see #135).

**Comment by Eldriitch** [comment]
> [](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types)
> 
> `Board` is a class, so instances of it are reference types. The behavior you're describing is expected in C#. To get what you want, you'd need to make an actual copy of the board rather than a reference to it.

Ah I see, so it's a C# bug instead -_- /s

I'll choose not to go on rant about how that's an absolutely *awful* design decision and just fix my code I guess...
