### ISSUE TITLE
Getting a Raylib error when trying to build

### ISSUE THREAD

**Issue by Ephraim225** [SebLague/Chess-Challenge#263]
![image](https://github.com/SebLague/Chess-Challenge/assets/58414822/be5e1d29-d7c6-49d4-ab89-0ba83dbe3774)

I'm using Visual Studio 2022 on Windows 7 if it matters. Might be missing something I haven't installed? Anyone know?

**Comment by R0b3rt1337** [comment]
Do you have an antivirus installed, and if so have you tried turning it off?

**Comment by gabeball** [comment]
I am getting the same issue:

C:\Users\HoldBaker\Documents\Chess-Challenge-main\Chess-Challenge\Chess-Challenge.csproj : error NU1101: Unable to find package Raylib-cs. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
1>Done building project "Chess-Challenge.csproj" -- FAILED.

**Comment by gabeball** [comment]
Copied solution from other user who had the same issue:
I managed to get it working.

Project > Manage NuGet Packages > Settings Cog (top right of pane)
Add a new source: Name: nuget.org, Source: https://api.nuget.org/v3/index.json
Click Ok
NuGet "Browse" tab, search for "raylib" and install raylib and raylib-cs

I feel like this should be the 2nd or 3rd bullet point in the "How to Participate" section of the README

**Comment by R0b3rt1337** [comment]
> I am getting the same issue:
> 
> C:\Users\HoldBaker\Documents\Chess-Challenge-main\Chess-Challenge\Chess-Challenge.csproj : error NU1101: Unable to find package Raylib-cs. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages 1>Done building project "Chess-Challenge.csproj" -- FAILED.

Are you sure this is the same error? In the screenshot it looks like Raylib was found but couldn't load a resource, unlike your issue where Raylib could not be found at all.

**Comment by jonigrin** [comment]
@Ephraim225 שלום
can close it now?

**Comment by Ephraim225** [comment]
> Copied solution from other user who had the same issue: I managed to get it working.
> 
> Project > Manage NuGet Packages > Settings Cog (top right of pane) Add a new source: Name: nuget.org, Source: https://api.nuget.org/v3/index.json Click Ok NuGet "Browse" tab, search for "raylib" and install raylib and raylib-cs
> 
> I feel like this should be the 2nd or 3rd bullet point in the "How to Participate" section of the README

This doesn't appear to be the issue I'm having. That source is already present in the project's package sources.

**Comment by AntVil** [comment]
i could fix it using this:

https://stackoverflow.com/questions/68283730/error-nu1100-unable-to-resolve-microsoftofficecore-15-0-0-for-net5-0

**Comment by Ephraim225** [comment]
UPDATE: Someone found a fix. See #75 

Long and short of it is if you replace the raylib.dll with the one that uses OpenGL 2.1 instead of 3.3 it should run then. If you are getting this issue that's the solution!
