### ISSUE TITLE
Lots of ambiguous reference errors

### ISSUE THREAD

**Issue by Magnus24112** [SebLague/Chess-Challenge#277]
I don't think I changed anything in my code that would create this issue

![image](https://github.com/SebLague/Chess-Challenge/assets/56786591/a63f9614-579e-4234-8946-60b856afe024)
![image](https://github.com/SebLague/Chess-Challenge/assets/56786591/ef120423-4975-4e34-8bb3-fa2235eeb3dc)

**Comment by ateready** [comment]
ChessChallenge.Chess is the namespace causing the confusion. Remove it.

Only ChessChallenge.API, and 4 system namespaces are allowed for the challenge. I got this myself, I think it's something to do with Visual Studio's intellicode automatically adding the namespace at some point.

**Comment by Magnus24112** [comment]
Thx dude!
