### ISSUE TITLE
Legal move marked as "illegal"

### ISSUE THREAD

**Issue by AndreyVarvar** [SebLague/Chess-Challenge#278]
Program says my bot made an illegal move, even thought it is totally legal.

<img width="568" alt="Screen Shot 2023-07-24 at 13 41 53" src="https://github.com/SebLague/Chess-Challenge/assets/91492313/5622129e-224e-47ec-896b-e0595102f304">

Here, the bot tried to play "e7b7", which is totally a legal move, but marked as "illegal" by the program.

<img width="571" alt="Screen Shot 2023-07-24 at 13 43 50" src="https://github.com/SebLague/Chess-Challenge/assets/91492313/f6dff764-ef7e-4992-80f5-4539ef0d21a8">

"g2f1" - again, illegal for the program, but actually legal.

My guess, is that whenever you miss a mate in 1 the move is considered "illegal", at least that's a pattern i noticed.
Now, i am not saying that ignoring a mate in 1 will ALWAYS result in an error (since i did not test that), but rather that all of the "illegal" moves were linked to that "ignore of mate in 1". The error may be linked to something else, which somehow involves missing the mate in 1.

**Comment by YesilHiyar** [comment]
same is happening to me ^^

**Comment by AndreyVarvar** [comment]
[MyBot.cs.zip](https://github.com/SebLague/Chess-Challenge/files/12145779/MyBot.cs.zip)

here is the code to try and reproduce the problem. Just make it play against Evil bot, and eventually the error will come up. It usually doesn't take long, around 5-6 matches, that are played super fast.
