### ISSUE TITLE
Inconsistency with Move printing

### ISSUE THREAD

**Issue by Martinetto33** [SebLague/Chess-Challenge#279]
I'm storing the last move made by my bot and I simply try to print it on my terminal. To do this I'm using the Move.StartSquare.Name and Move.TargetSquare.Name methods.

The thing is, the values printed on the terminal don't seem to match at all any of my bot's moves, not even mine. Here's an example, where I expect moveToDo to contain the move a8→b8 as the black rook moves to the right:

![ytr56yt](https://github.com/SebLague/Chess-Challenge/assets/107687192/16048035-85f1-4051-9524-bf5f3ea1a750)

**Comment by Disservin** [comment]
You can just use move.ToString()

**Comment by Martinetto33** [comment]
Perfect, thank you for your help!
