### ISSUE TITLE
Are we allowed multiple submissions?

### ISSUE THREAD

**Issue by WilliamAlecBrannon** [SebLague/Chess-Challenge#28]
If we keep tinkering with our code and find a "better" solution, are we allowed to submit updated bots?

**Comment by Encrux** [comment]
In the video Sebastian said you can continuously update your solution until the deadline.

**Comment by SebLague** [comment]
Just wanted to note here that I've updated the rules to allow for two bots to be submitted, but request that you only do so if you feel that the two bots are significantly different from one another.
