### ISSUE TITLE
Request: API access to 50 move rule counter

### ISSUE THREAD

**Issue by R0b3rt1337** [SebLague/Chess-Challenge#283]
Accessing the 50 move rule counter for a Board instance is currently not possible as far as i know. This could be very helpful in calculating the evaluation during endgames using `(eval * (100 - fiftyMoveCounter) / 100`, to ensure the engine is making progress instead of shuffling around until suddenly every move is 0. Would like to see this added if you have time to do so.

**Comment by SebLague** [comment]
Added in latest version, thanks for the suggestion
