### ISSUE TITLE
illegal move happens from nowhere

### ISSUE THREAD

**Issue by jonigrin** [SebLague/Chess-Challenge#284]
sometimes the game just crashes and said that my bot tried to do an illegal move, I saw in another issue it's because the bot doesn't undo moves sometimes so I made sure it never happens, the only moves I do are pulled out from the function board.GetLegalMoves()
uploded the main 2 functions (Think just calls them) and also the only two times I call board.make (I did ctrl+f)
![image](https://github.com/SebLague/Chess-Challenge/assets/115393807/0efd347c-667e-4a0c-8c05-ae035811b891)
![image](https://github.com/SebLague/Chess-Challenge/assets/115393807/e5fc9114-07fb-47af-8468-0a4cfd197640)

**Comment by R0b3rt1337** [comment]
Do you make and unmake moves in your Eval function? If not, could you send the entire stacktrace you are getting?
