### ISSUE TITLE
Is there a way to check if either player is castled?

### ISSUE THREAD

**Issue by stockfishIsBad** [SebLague/Chess-Challenge#286]

**Comment by jonigrin** [comment]
you can check if one of the players has his king and the matching rook in the correct position
or check if both has the right to castle both sides
but both have flows (if you check positions maybe they moved there manually and if you check right to castle maybe they moved somewhere so they don't have the right anymore)

**Comment by icecream17** [comment]
you can check

```
public bool board.HasKingsideRight(bool white)
public bool board.HasQueensideRight(bool white)
```

**Comment by mcthouacbb** [comment]
If the player manually moves their king and rook to the correct positions, does that count as castling? There's no way to tell the difference between that and an actual castle move

**Comment by AdityaMeena001** [comment]
> If the player manually moves their king and rook to the correct positions, does that count as castling? There's no way to tell the difference between that and an actual castle move

that would not count as castling, 
`public bool HasKingsideCastleRight(bool white)
public bool HasQueensideCastleRight(bool white)`

are there to check if the king can castle as in response to a move.

**Comment by mcthouacbb** [comment]
@AdityaMeena001 Why would that not count as castling? If you were given both positions there is absolutely no way to tell, and the evaluation should be exactly the same.

**Comment by SebLague** [comment]
There's no built in way to do this -- you could either look at the king and rook positions yourself as others have said, or loop over the game history and see if either side made a castling move.
