### ISSUE TITLE
[Feature request] update SquareIsAttackedByOpponent to allow checking for either player, or update TrySkipMove to optionally skip even if in check

### ISSUE THREAD

**Issue by RobotLazerShark** [SebLague/Chess-Challenge#298]
Possible duplicate of https://github.com/SebLague/Chess-Challenge/issues/296

What I'm trying to do is rank possible moves based on (among other things) what the impact is on the number of pieces being threatened with capture. To do this, I was trying to use the SquareIsAttackedByOpponent, but that always assumes the perspective of whoever's turn it is. Then I thought about using TrySkipMove, but that won't work if the current player is in check.

As far I can tell, there's currently no (easy or simple) way for me to check which pieces I could potentially capture on a followup turn when I am in check on the current turn.
As an example, I would like to have my bot choose this move:
![image](https://github.com/SebLague/Chess-Challenge/assets/13001606/8765e3ff-dcfc-435b-bbee-69b0588aad13)
over this move:
![image](https://github.com/SebLague/Chess-Challenge/assets/13001606/96b866a2-6621-4c12-94ee-34dbdbfa8d09)

**Comment by SebLague** [comment]
I have added the function ForceSkipTurn() to the board class. Thanks for the suggestion!
