### ISSUE TITLE
How to check if castling is legal

### ISSUE THREAD

**Issue by Marki2019** [SebLague/Chess-Challenge#300]
HasQueensideCastleRight and HasKingsideCastleRight only check if castling is available, not legal. how would you check if the move is legal (code snippet if possible if not doesn't matter <3)

**Comment by jonigrin** [comment]
well, you could create the castle move using the Move constructor and then check if this is in the legal moves array

**Comment by SebLague** [comment]
You could do what @jonigrin says, or loop over the legal moves and check the IsCastles property on each move
