### ISSUE TITLE
Is there a way to set a move to "null" until search is over?

### ISSUE THREAD

**Issue by stockfishIsBad** [SebLague/Chess-Challenge#31]

**Comment by CREAsTIVE** [comment]
Struct are not-nullable type. But you can do Move?
![image](https://github.com/SebLague/Chess-Challenge/assets/62616308/9a99b196-fca2-4299-8dbf-ab438fe3da72)

**Comment by CREAsTIVE** [comment]
Then you can convert it back to not-nullable type like this
![image](https://github.com/SebLague/Chess-Challenge/assets/62616308/209c6b17-5c7c-4e0c-84b9-48be382eb7d2)

**Comment by SebLague** [comment]
You can do Move move = Move.NullMove; And you can test if it's null with move.IsNull;
Note this isn't technically null in the normal sense (it's just the move struct's representation of an invalid move), but I imagine it would work for what you need? Otherwise you can do what @CREAsTIVE mentioned.
