### ISSUE TITLE
Suggestion: Allow users to control which lines to consider for brain capacity.

### ISSUE THREAD

**Issue by Gourab-Ghosh** [SebLague/Chess-Challenge#314]
There are certain lines in code which are only used for debugging purposes. Like printing score, number of nodes searched, etc. But these code takes brain capacity and each and every time I need to comment out these lines and then check brain capacity and then again undo the changes. A possible solution to this could be that users can add ```// Ignore Line``` at the end of the line and the brain capacity calculator should pretend like the line does not exist. Having this or some similar feature greatly increases the productivity.

**Comment by Gourab-Ghosh** [comment]
> I would just write your Bot first ignoring the capacity but try to not be too verbose in what you do. And when you are happy with the result start shrinking everything down. Otherwise you could implement that logic yourself in CountTokens via token.Span and using that: `code.Substring(token.End).Split(Environment.NewLine).FirstOrDefault()?.TrimEnd().EndsWith("// ignore line") == true` (not tested, just as an idea)

There are so many optimisations and improvements one can implement in a chess engine. But with this limited brain capacity it is never possible to implement all of them. So whenever I find a new idea to shorten the code, I always check if new optimisations which are 2-3 lines to implement can be added to the code. So first writing the code and optimising its size is not applicable for me. Also reducing the brain capacity later is not a good idea for me because after completely testing my engine performance with the final code, I may have to remove few features because of brain capacity. Also thanks for your help but I have started coding in C# because of this project and so after 3 days of coding, I am still not experienced enough to understand how and where to implement your code. Anyways thanks for your suggestion.

**Comment by EikeSchwass** [comment]
@Gourab-Ghosh just replace the TokenCounter.cs with this [TokenCounter.cs](https://gist.github.com/EikeSchwass/ed856f39584491eb999284c17af62711). You can find the original TokenCounter in [...]\Chess-Challenge\src\Framework\Application\Helpers\Token Counter\TokenCounter.cs

**Comment by Gourab-Ghosh** [comment]
> @Gourab-Ghosh just replace the TokenCounter.cs with this [TokenCounter.cs](https://gist.github.com/EikeSchwass/ed856f39584491eb999284c17af62711). You can find the original TokenCounter in [...]\Chess-Challenge\src\Framework\Application\Helpers\Token Counter\TokenCounter.cs

Thanks for this. This totally worked. Still I want this feature to be implemented in the repo, so that I don't need to copy it again and again for every new version. Anyways thanks for this. This works great.

**Comment by folke** [comment]
You can already do this:

```csharp
#if DEBUG
        Console.WriteLine("Helllo");
#endif
```

That code will still be executed, but won't be counted as tokens

**Comment by Gourab-Ghosh** [comment]
> You can already do this:
> 
> ```cs
> #if DEBUG
>         Console.WriteLine("Helllo");
> #endif
> ```
> 
> That code will still be executed, but won't be counted as tokens

I have directly pasted this code into the Think function and it didn't count tokens but unfortunately the code did not print Hello in the terminal. I am completely new to C# and so I don't even know if I was supposed to do that or something else with the code. But whatever I did, it unfortunately didn't work.

**Comment by folke** [comment]
Just run the project with debug, not as a release version

**Comment by Gourab-Ghosh** [comment]
> Just run the project with debug, not as a release version

So instead of running the project in the debug mode, I changed `#if DEBUG` to `#if RELEASE` and everything seems to work and also it is not counted as tokens. Just want to confirm from you if everything is good before I close the issue.

**Comment by folke** [comment]
hmm, if that's the case then @SebLague will have to take this into account, or people would be able to cheat tokens :)

Probably because the parses has no `DEFINE`s.

**Comment by Gourab-Ghosh** [comment]
> hmm, if that's the case then @SebLague will have to take this into account, or people would be able to cheat tokens :)
> 
> Probably because the parses has no `DEFINE`s.

Actually I have tested this for a while. This is working great. But I don't want to run my project in debug mode for testing as I am testing the engine performance. So in some cases vs code is giving ugly red warnings that some variables are not defined. The variables I made temporarily for testing and tweaking, which I will replace with the original value while submitting. And also I don't want to disable vs code error messages as it is really useful. So for that although this feature is great, I still want some comment based line ignoring feature which I have suggested. So currently I am not planning to close the issue. Anyways, Thanks for you help :)

**Comment by hypnotox** [comment]
> > @Gourab-Ghosh just replace the TokenCounter.cs with this [TokenCounter.cs](https://gist.github.com/EikeSchwass/ed856f39584491eb999284c17af62711). You can find the original TokenCounter in [...]\Chess-Challenge\src\Framework\Application\Helpers\Token Counter\TokenCounter.cs
> 
> Thanks for this. This totally worked. Still I want this feature to be implemented in the repo, so that I don't need to copy it again and again for every new version. Anyways thanks for this. This works great.

You can just change it once for your local version and then develop in there, it won't be overwritten just like that. 

I, for example, have modified the UI and engine code heavily for debugging purposes and regularly merge upstream if there are new commits.
I'll test my bot in a fresh project when I'm finished, to ensure everything fits and works correctly, but otherwise I'm using my "dev build" for iterative development of my bot(s).

**Comment by Gourab-Ghosh** [comment]
> > > @Gourab-Ghosh just replace the TokenCounter.cs with this [TokenCounter.cs](https://gist.github.com/EikeSchwass/ed856f39584491eb999284c17af62711). You can find the original TokenCounter in [...]\Chess-Challenge\src\Framework\Application\Helpers\Token Counter\TokenCounter.cs
> > 
> > 
> > Thanks for this. This totally worked. Still I want this feature to be implemented in the repo, so that I don't need to copy it again and again for every new version. Anyways thanks for this. This works great.
> 
> You can just change it once for your local version and then develop in there, it won't be overwritten just like that.
> 
> I, for example, have modified the UI and engine code heavily for debugging purposes and regularly merge upstream if there are new commits. I'll test my bot in a fresh project when I'm finished, to ensure everything fits and works correctly, but otherwise I'm using my "dev build" for iterative development of my bot(s).

As I don't have much experience in neither C# nor github. In github I only know how to make repo and upload files and how to clone repo. So, I don't want to get involved with merging the new version code with the old one. So for each version I download the new version and then copy-paste the code of my bot into the new version. For now cloning new version and copying code works better for me until I start learning all the great features of github. So I still need to copy the TokenCounter.cs code from this issue again and again. And I don't have much problem copying code of two files. But in future if the code of TokenCounter.cs is updated, I would have no idea how to implement the `// ignore line` feature again in the new code. For that I want this feature implemented in the repo.

**Comment by SebLague** [comment]
Hi @Gourab-Ghosh I will be adding official support for this soon

**Comment by SebLague** [comment]
Added in v1.17
