### ISSUE TITLE
`namespace` clarification

### ISSUE THREAD

**Issue by lue-bird** [SebLague/Chess-Challenge#318]
I'm guessing you can't put the `class MyBot` in a `namespace` but extra clarification can't hurt :).
Various namespaces could save small amounts of tokens, for example instead of
```csharp
using System.Collections.Generic;
using ChessChallenge.API;
using Squares = System.Collections.Generic.IEnumerable<ChessChallenge.API.Square>;

class MyBot
```
you could write
```csharp
using System.Collections.Generic;
using ChessChallenge.API;
namespace Something
{
using Squares = IEnumerable<Square>;
class ByBot
}
```
or even tinier
```csharp
using System.Collections.Generic;
namespace ChessChallenge.API
{
using Squares = IEnumerable<Square>;
class ByBot
}
```
Thanks for organizing this event :hugs:

**Comment by SebLague** [comment]
Yes you may not put the MyBot class inside a namespace. I'll clarify this in the rules, thanks for the question.
