### ISSUE TITLE
consider not counting `SyntaxKind.StaticKeyword`

### ISSUE THREAD

**Issue by lue-bird** [SebLague/Chess-Challenge#324]
Proposed: The keyword `static` doesn't add capabilities to your code and should not be counted as a token.

Adding `static` is sometimes necessary
```csharp
int[] Signs = new[] { -1, 1 };

Movement movementDirectionsDiagonal =
    Signs.SelectMany(file => Signs.Select(rank => (file, rank)));
```
the compiler complains
> A field initializer cannot reference the non-static field, method, or property 'MyBot.Signs'

**Comment by SebLague** [comment]
I agree that static could reasonably be excluded, but I've decided not to make further changes to the token counter at this point
