### ISSUE TITLE
Is 'GetSliderAttacks' inclusive or exclusive the blockers?

### ISSUE THREAD

**Issue by qfeys** [SebLague/Chess-Challenge#338]
In the version of the function where I can give the blockers via a Bitboard, will the blockers themselves be marked as reachable or unreachable?
It would be advantageous for me if they were marked as reachable, as that way I can mark these squares as protected by the piece.

**Comment by qfeys** [comment]
I have found the solution myself. For those interested, it is including the blockers, both allied and hostile.
It would be nice if the documentation could be changed to indicate this.

**Comment by mcthouacbb** [comment]
Not sure if you need this, but the reason blockers is included is so that sliding piece captures can be easily added during move generation without extra work. Removing moves that capture your own pieces is done simply by masking them out with and and not.

**Comment by qfeys** [comment]
Yeah, that's how I wanted to use it, so it works perfect to me. It is just that the documentation doesn't specify which it is, and I had initially guessed the opposite, so I was stuck figuring it out the hard way.

**Comment by SebLague** [comment]
I'll see about clarifying the docs on this later, thanks for the suggestion.
