### ISSUE TITLE
Moved piece becomes Null when using board.MakeMove()

### ISSUE THREAD

**Issue by Barigamb738** [SebLague/Chess-Challenge#34]
I made a simple eval script to add up the values of the pieces but for some reason the piece that just moved becomes a null piece
![image](https://github.com/SebLague/Chess-Challenge/assets/54997181/6de84e54-ceee-4df2-8574-b1c1d8422cff)
![image](https://github.com/SebLague/Chess-Challenge/assets/54997181/ff1bc3c7-90cd-4dd4-8e56-76abc40aa8fe)
As you can see here one of the White Knights becomes a Null
I used this code:
```cs
int eval = 0;
board.MakeMove(move);

foreach (PieceList piecelist in board.GetAllPieceLists())
{
    foreach (Piece piece in piecelist)
    {
        eval += pieceValues[(int)piece.PieceType]*(isWhite == piece.IsWhite ? 1 : -1);
        Console.WriteLine(piece.ToString() + " : " + pieceValues[(int)piece.PieceType]*(isWhite == piece.IsWhite ? 1 : -1));
    }
}

board.UndoMove(move);
```

**Comment by rtz981** [comment]
I am also having the same problem, and what makes it worse is that if the move was a capture, then there is no null piece.

**Comment by WilliamAlecBrannon** [comment]
How did you get the console output to collapse like that?

**Comment by Barigamb738** [comment]
> How did you get the console output to collapse like that?

idk it's probably a VSCode setting lol

**Comment by MamamYeayea** [comment]
BUMP. Any1 find solution ?

**Comment by rtz981** [comment]
I fixed it by introduing a variable _lastMove_.
Then I added this into my evaluate function:
```
int type = (int)piece.PieceType;
if (type == 0) type = lastMove;
```
And I also set the _lastMove_ variable before I make the move:
```
lastMoved = (int)board.GetPiece(move.StartSquare).PieceType;
board.MakeMove(move);
```
Hope it works!

**Comment by SebLague** [comment]
Hi I've uploaded a fix for the GetPiece function. I apologise for the error!
