### ISSUE TITLE
How to properly edit Fens.txt

### ISSUE THREAD

**Issue by SKAE5** [SebLague/Chess-Challenge#346]
It looks like no matter how I edit the Fens.txt file, the board always starts at starting position, instead of the one I put at the first line in the file

**Comment by Tjalle-S** [comment]
For some reason, the IDE doesn't recognise editing the Fens.txt file as editing the project, so it doesn't rebuild. Going to Build -> Rebuild Solution will fix this (at least, this is how I fixed it, using Visual Studio). Keep in mind that it will take the first FEN string from the list as starting position.

**Comment by SKAE5** [comment]
> For some reason, the IDE doesn't recognise editing the Fens.txt file as editing the project, so it doesn't rebuild. Going to Build -> Rebuild Solution will fix this (at least, this is how I fixed it, using Visual Studio). Keep in mind that it will take the first FEN string from the list as starting position.

This worked, thank you!
