### ISSUE TITLE
Clarification on the match

### ISSUE THREAD

**Issue by lucasmeneghin** [SebLague/Chess-Challenge#35]
What are the tournament details?
Is it all x all? Is it by brackets? Do you get white and black vs your opponent or not necessarily? Do all positions start from initial position, or are other preset positions?

**Comment by lucasmeneghin** [comment]
Also, as a bullet player
Can you berserk 😁?

**Comment by cdrch** [comment]
I wonder how difficult it would be to run a mass round-robin setup, taking a Stockfish (or whatever) instance to scan through the replays and picking the closest games (or whatever might make it more "interesting") to offer for humans to then view.

**Comment by Ardnij123** [comment]
On that note, is only the win/loss going to count or is the difference in score also going to count?

**Comment by lucasmeneghin** [comment]
Mostly likely win/loss only, i guess
A win is a win, no matter the material difference. You can win even if behind on material

**Comment by SebLague** [comment]
Tournament details are TBD (depends on number of entries). The games will almost definitely be from starting position though (at least for tournament, if a 1v1 is required for tiebreaks or something, then that may be from random positions).
