### ISSUE TITLE
choosing illegal moves

### ISSUE THREAD

**Issue by PotatMuffin** [SebLague/Chess-Challenge#36]
it would be possible to look through all the pieces on the board and just choose a move (that isn't legal) that removes the opponents queen or one of their rooks.
the rules also do not state that this is not allowed.

**Comment by mcthouacbb** [comment]
This doesn't seem to be a problem. ChallengeController.OnMoveChosen validates whether the move is legal, and an illegal move counts as an automatic instant win for the opponent
