### ISSUE TITLE
Consider adding rule

### ISSUE THREAD

**Issue by EikeSchwass** [SebLague/Chess-Challenge#366]
I would propose that all participants must agree to have their bots source code published. One of the biggest knowledge gains of this competition will be from looking at other bots code. 

Just so noone complains afterwards the rules should include that participation agreement

**Comment by Firestorm-253** [comment]
> I would propose that all participants must agree to have their bots source code published. One of the biggest knowledge gains of this competition will be from looking at other bots code.
> 
> Just so noone complains afterwards the rules should include that participation agreement

I def will never show my code pre challenge end.
But i agree that u could and should show the code of the bots you show off in the video.
So submitting your code should include that you agree that it will be published ye. @SebLague

**Comment by SebLague** [comment]
On the submission page there is a mandatory checkbox to agree that all submitted data may be publicly displayed in the video / accompanying project.

**Comment by Firestorm-253** [comment]
> On the submission page there is a mandatory checkbox to agree that all submitted data may be publicly displayed in the video / accompanying project.

Oh sry, perfect!
This issue shall be closed then @EikeSchwass
