### ISSUE TITLE
GameMoveHistory does not contain historical moves

### ISSUE THREAD

**Issue by StechWasTaken** [SebLague/Chess-Challenge#369]
When the board is initialized with a fen string, it doesn't contain the historical moves.

I don't think it needs to be solved, but should be disclosed in the doc.

![image](https://github.com/SebLague/Chess-Challenge/assets/41377140/31d9f517-a597-4369-9d4e-ebee1d42935f)

![image](https://github.com/SebLague/Chess-Challenge/assets/41377140/7d922726-8b21-421d-8694-4e75d3a12593)

**Comment by SebLague** [comment]
That's true, a fen string doesn't contain any move info so it cannot recreate the historical moves with that function. I'll think about adding it to the docs, thanks for the suggestion.
