### ISSUE TITLE
Lichess.org intergration

### ISSUE THREAD

**Issue by kabrownie** [SebLague/Chess-Challenge#371]
hello ,
Is there a way to integrate the bot to lichess.
I was hoping that after finishing creating my bot a I should be able to upload it to [lichess](lichess.org)

**Comment by SebLague** [comment]
Hi, once the challenge is complete I might work on creating a simple way to integrate the bots with lichess. If you want to do it before then, you could try asking for advice in the discord server (you can find a link in the readme)

**Comment by kabrownie** [comment]
ok thanks,
