### ISSUE TITLE
IsCapture flag is false for enpassant moves

### ISSUE THREAD

**Issue by Zadmur** [SebLague/Chess-Challenge#372]
For example after the moves
1. e4 Nf6
2. Nf3 Rg8
3. e5 d5

The enpassant move to d6 has the flag IsEnPassant true, but the move is also a capture, thus I think
it should also have IsCapture true, which atm. is false.

**Comment by SebLague** [comment]
Hi, could you please make sure that you have updated the project to the latest version, I believe this bug was fixed in 1.15

**Comment by Zadmur** [comment]
Seems to be working in the latest, btw. latest seems to be much slower than 1.12 that I was previously using.
