### ISSUE TITLE
Can I build a virtual 'computer' and then run a program stored inside a variable

### ISSUE THREAD

**Issue by alxndr2000** [SebLague/Chess-Challenge#374]
I planned on writing a system to interpret an array of 64bit numbers as a program and then run that. All the code would be within the rules as I understand them and the whole thing would be documented.
I'm unsure if this goes against the rules or if the rules would be changed to ban this approach.

I'm also aware that this approach would probably be slow however I want to do it this way to challenge myself more than to win

Thanks

**Comment by SebLague** [comment]
Yes this is allowed. I look forward to seeing what you come up with :)
