### ISSUE TITLE
Look at opponent moves

### ISSUE THREAD

**Issue by DraizaClaw** [SebLague/Chess-Challenge#379]
I use a for loop to look for every legal move and if one of them is a capture then the bot will play it. I want it to be so that the bot takes if the opponent cannot capture back. (I will implement trades later but I need to know how to cycle through the opponent's moves)

**Comment by an-inconspicuous-semicolon** [comment]
It sounds like you are looking for the `Board.SkipMove()` function

**Comment by loki12241224** [comment]
if you use board.MakeMove(Capture) and then use board.GetLegalMoves(True) that will return all legal captures your opponent could make. it would then be as simple as checking if any of those captures are of the piece you just moved.

**Comment by DraizaClaw** [comment]
![image](https://github.com/SebLague/Chess-Challenge/assets/80351510/e59e3b3c-7c0c-4c65-b9a1-73ed753a4e4a)

this is my code
i made a list called goodmoves that are moves that dont end in a draw after one move
it uses board.makemove()
the second for loop should go through everymove an opponent can make
if one of them makes my bot want to draw, it will not play said move and go through another
the moves that are classified to end badly for the bot will be removed from a another list called better moves

**Comment by androur** [comment]
Can you plz send me part of code with list goodmoves, I don't know how to make a list of elements type Move[] so I will be more then happy if you help me by doing that.
