### ISSUE TITLE
Using stockfish for training a neural network

### ISSUE THREAD

**Issue by tact1m4n3** [SebLague/Chess-Challenge#38]
Is it allowed to train a neural network using board evaluations emitted by stockfish? Because tbh that doesn’t seem fair :))

**Comment by CREAsTIVE** [comment]
i m think yes, but all youre neural network data requires to be inside MyBot.cs file

**Comment by JukoiDev** [comment]
> i m think yes, but all youre neural network data requires to be inside MyBot.cs file

your english is very bad

**Comment by CREAsTIVE** [comment]
> > i m think yes, but all youre neural network data requires to be inside MyBot.cs file
> 
> your english is very bad

i know xd

**Comment by SebLague** [comment]
Yes this is allowed!
