### ISSUE TITLE
hardware used for final tournament 

### ISSUE THREAD

**Issue by an-inconspicuous-semicolon** [SebLague/Chess-Challenge#381]
High there, I was wondering if I would be able to find out the final hardware being used for the tournament.

My bot uses a calculation budget that is based on evals/sec, and since this changes based on the processors speed and cache I think it would be useful to know in advance.

**Comment by Moreno-Gentili** [comment]
I agree, this information is needed.

> If you have added a constructor to MyBot (for generating look up tables, etc.) it may not take longer than 5 seconds to complete.

How many computations are in "5 seconds"? You should include a CPU-intensive method that's taking roughly 5 seconds on the hardware you'll be using for the tournament. So, when we run it on our machines and measure the time it took to complete, we get a quick estimate about how our hardware compares to yours.

**Comment by SebLague** [comment]
Hi, the tournament will be run on an i7-2700h (2.3GHz). Here is a bot that takes about 5 seconds per move on that hardware as a rough reference:

```
using ChessChallenge.API;
using System;

public class MyBot : IChessBot
{
    Board testBoard;
    public Move Think(Board board, Timer timer)
    {
        string fen = "r3k2r/1ppb1ppp/2n1p3/1q6/3PN3/2PPp3/PpQ2PPP/R3K2R w KQkq - 0 16";
        testBoard = Board.CreateBoardFromFEN(fen);
        var sw = System.Diagnostics.Stopwatch.StartNew();
        Search(5);
        sw.Stop();
        Console.WriteLine(sw.ElapsedMilliseconds + " ms.");
        return board.GetLegalMoves()[0];
    }

    void Search(int depthRemaining)
    {
        if (depthRemaining == 0)
        {
            return;
        }

        Span<Move> moves = stackalloc Move[218];
        testBoard.GetLegalMovesNonAlloc(ref moves);

        foreach (var m in moves)
        {
            testBoard.MakeMove(m);
            Search(depthRemaining - 1);
            testBoard.UndoMove(m);
        }
    }
}
```

**Comment by an-inconspicuous-semicolon** [comment]
Thank you, this will be very useful for me.

and _man_ there must be something up with my pc, because my 5800x3d is taking 6 seconds :(

**Comment by kevinzhao14** [comment]
Hi, don't mean to use this for debugging but the provided benchmark bot is taking ~30 seconds on my 5800X, which is quite a bit longer than it should take. AFAIK, my cpu works fine with other tasks. Any ideas?

**Comment by kevinvermaat** [comment]
Wow haha, 34122 ms for me.

**Comment by an-inconspicuous-semicolon** [comment]
> Wow haha, 34122 ms for me.

oof, what hardware?

**Comment by kevinzhao14** [comment]
> Wow haha, 34122 ms for me.

Make sure you're running in release mode, made the same mistake.

**Comment by kevinvermaat** [comment]
> > Wow haha, 34122 ms for me.
> 
> oof, what hardware?

hahah well, M2 processor macbook. But i'm not running in release mode i guess! Will let you know when i tried release mode.

**Comment by kevinzhao14** [comment]
> > > Wow haha, 34122 ms for me.
> > 
> > 
> > Make sure you're running in release mode, made the same mistake.
> 
> :D how to do that? :)

If you're using VS, I believe there's an option somewhere, you'll have to look it up. If you're using command line, you can do `dotnet run --configuration Release`

**Comment by kevinvermaat** [comment]
> > > > Wow haha, 34122 ms for me.
> > > 
> > > 
> > > Make sure you're running in release mode, made the same mistake.
> > 
> > 
> > :D how to do that? :)
> 
> If you're using VS, I believe there's an option somewhere, you'll have to look it up. If you're using command line, you can do `dotnet run --configuration Release`

4294 ms.
:D makes more sense haha
