### ISSUE TITLE
Is there a way to know if a new game has started?

### ISSUE THREAD

**Issue by Sparxl** [SebLague/Chess-Challenge#385]
I want to clear all move heuristics in case the current game ends and a new game starts. Is there any way to do this?

**Comment by FrederoxDev** [comment]
board.PlyCount would be 0 or 1 when it's your bots first move

**Comment by Kreb08** [comment]
You get a new Instance of your bot for each game, non static values will be reset by default. You could use a constructor to reset static values like this `public MyBot() { value = 0; }`
Also keep in mind when playing against the evil bot most of the games start from a random position where board.PlyCount > 1
