### ISSUE TITLE
How would we go about using neural networks in this project?

### ISSUE THREAD

**Issue by michaelbzms** [SebLague/Chess-Challenge#397]
Suppose I were to train a simple neural network using python to use in my AI. How would I be able to use it in this project? 

I am not familiar with C#, so I am trying to see if such an approach would be viable. Is there a matrix multiplication library in C# that we are allowed to use? How do we set the weights of these matrices?

**Comment by AugsEU** [comment]
The program has to be in 1024 tokens. Each weight in your network would occupy some tokens, so I think most people agree that it's not possible to fit a good NN into this limit.

**Comment by michaelbzms** [comment]
I see. Yes, even for logistic regression, we would need at least 768 weights/tokens (768 being the input dimension).
