### ISSUE TITLE
IsDraw() is never returning true when a position is a draw

### ISSUE THREAD

**Issue by loki12241224** [SebLague/Chess-Challenge#400]
`public Move Think(Board board, Timer timer)
    {
        isWhite = board.IsWhiteToMove;
        Tuple<Move, float> BestMove = MiniMax(board, 4, -100000, 100000, true);
        Console.WriteLine("ChosenMove: " + BestMove);
        Console.WriteLine("-=-=-=-=-=-=-=-=-=-=-");
        board.MakeMove(BestMove.Item1);
        if (board.IsDraw())
        {
            System.Threading.Thread.Sleep(1000000);
        }
        
        return BestMove.Item1;
    }`

this never sleeps when a drawing position occurs. i cannot get IsDraw() to return true.

**Comment by mcthouacbb** [comment]
If the position is a draw then the think function won't be called because the game is already over

**Comment by LooveToLoose** [comment]
There is a board.MakeMove before the Draw check, though, so it should go off if the next move results in a draw, right? Same issue here.

My guess would be that the problem might have something to do with the MiniMax search? Maybe if a piece is taken the repetition table is cleared but not reinstantiated when the move is undone? Something like that?

**Comment by SebLague** [comment]
This should be fixed in the latest version, sorry about that!

**Comment by tom-anders** [comment]
thank you so much, I kept wondering which commit would suddenly make my AI draw all the time - guess i should just use `git pull` instead of `git pull --rebase` next time

**Comment by loki12241224** [comment]
The newest update to the file seems to have fixed the issue.
