### ISSUE TITLE
Disabling token counter to remove the pause on start

### ISSUE THREAD

**Issue by oauo** [SebLague/Chess-Challenge#41]
Checking memory requirements at the start adds quite a long pause between trials, which I don't need right now.

I tried going into places like TokenCounter.cs and making it return 0 immediately but the pause persists.

**Comment by CREAsTIVE** [comment]
Change this line: https://github.com/SebLague/Chess-Challenge/blob/46ee1d6caf1e182fd42a0f060a56d63d7d23d610/Chess-Challenge/src/Framework/Application/Core/ChallengeController.cs#L58

**Comment by oauo** [comment]
Hmm, I guess it's not the token counter causing the pause

**Comment by oauo** [comment]
Not the token counter
