### ISSUE TITLE
Can't build the file

### ISSUE THREAD

**Issue by ejosephrogo** [SebLague/Chess-Challenge#414]
Am Trying to build through CMD but getting:

fatal error. System.accessviolationexception: attempted to read or write protected memory.

Am sorry, a little bit new to all these, if you can help out.

**Comment by Ephraim225** [comment]
Have a look at #75 and see if that's like what you're experienced. It sounds similar.

**Comment by ejosephrogo** [comment]
> Have a look at #75 and see if that's like what you're experienced. It sounds similar.

Yes thanks, although the fix is kind of challenging to me since am new to this but I'll find it out..
