### ISSUE TITLE
ChessChallenge.Chess.RepetitionTable crashes when game takes more then 256 plies

### ISSUE THREAD

**Issue by Skoolin** [SebLague/Chess-Challenge#415]
If the game takes longer than 256 plies, it crashes.
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ChessChallenge.Chess.RepetitionTable.Contains(UInt64 h) 
```

`int[] startindices` und `int[] hashes` are only of size 256.

proposal for a fix:
`hashes = new ulong[1024];` in `ChessChallenge.Chess.RepetitionTable`

**Comment by Skoolin** [comment]
We saw there is a bounds check in the Push method. `count++;` is not included inside the bounds check. if it where, it would not detect any repetitions after ply 256 has been reached.

**Comment by SebLague** [comment]
I've increased the size as proposed, thanks!
