### ISSUE TITLE
[BUG] Undoing a move does not decrease `Board.depth`

### ISSUE THREAD

**Issue by rokbok** [SebLague/Chess-Challenge#424]
`Board.depth` is increased in `MakeMove`, but not decreased in `UndoMove`. This leads to issues, at the very least in the following situation

- We have a board, and `IsDraw()` returns `false`
- We do a bunch of moves, and then undo them, getting back to the original position
- Now `IsDraw()` returns `true`, because the check `depth > 0` in `IsRepeatedPosition` returns `true`, when it returned `false` the first time around.

This could be related to #170. The reason I created a separate bug is that it is not clear that this is the only cause for #170.

**Comment by Draeggon** [comment]
I encountered the same problem.
Here is a minimal code snippet to reproduce behavior:
```cs
using ChessChallenge.API;
using System;

public class MyBot : IChessBot
{
    int[] pieceValues = { 0, 100, 300, 300, 500, 900, 10000 };

    public Move Think(Board board, Timer timer)
    {
        bool a = board.IsDraw();
        Move moveToPlay = ThinkHarder(board, board.IsWhiteToMove);
        bool b = board.IsDraw();


        if (a != b) // log if weirdness happen
        {
            Console.WriteLine(board.GetFenString());
            Console.WriteLine(moveToPlay);
            Console.WriteLine(board.IsInStalemate());
            Console.WriteLine(board.IsRepeatedPosition());
            Console.WriteLine(board.IsInsufficientMaterial());
            Console.WriteLine(board.IsFiftyMoveDraw());
        }

        return moveToPlay;
    }



    Move ThinkHarder(Board board, bool color)
    {
        Move[] allMoves = board.GetLegalMoves();
        Move moveToPlay = allMoves[0];

        foreach (Move move in allMoves)
        {
            board.MakeMove(move);
            board.UndoMove(move);
        }
        return moveToPlay;
    }
}
```

**Comment by SebLague** [comment]
Thank you, I've fixed the bug with the depth counter. Sorry about that!

**Comment by rokbok** [comment]
Absolutely no worries and thank you for the fix
