### ISSUE TITLE
Parallelism is still possible through the ParallelEnumerable.AsParallel Method because of LINQ

### ISSUE THREAD

**Issue by David-M-Nielsen** [SebLague/Chess-Challenge#43]
I feel like this should be forbidden, in the spirit of the rule:
"As implied by the allowed namespaces, you may not read data from a file or access the internet, nor may you create any new threads or tasks to run code in parallel/in the background."

**Comment by EikeSchwass** [comment]
I think that rule is pretty clear that multithreading in any way is forbidden, and that this should be obvious by the forbidden namespaces

**Comment by SebLague** [comment]
Thanks for pointing this out, I've updated the rules to make it clearer.
