### ISSUE TITLE
Is System.Math allowed?

### ISSUE THREAD

**Issue by ScottProgrammer** [SebLague/Chess-Challenge#431]
I see quite a few examples in this issue list using System.Math for Math.Min, Math.Max
it is not listed in the allowed namespaces
can we get an official verdict on if using it breaks the rules

it saves very needed tokens over writing a function like this
   public int Max(int Number1, int Number2)
    {
        if (Number1 > Number2)
            return Number1;
        return Number2;
    }
but don;t want to be disqualified for using the Math namespace

**Comment by ryanheath** [comment]
Yes it is allowed. #162 see [reply from Seb](https://github.com/SebLague/Chess-Challenge/issues/162#issuecomment-1646598380)
