### ISSUE TITLE
board.MakeMove doesnt change board.IsWhiteToMove

### ISSUE THREAD

**Issue by Gamaya0** [SebLague/Chess-Challenge#437]
Here the Bot has the black pieces, but board.MakeMove doesnt change board.IsWhiteToMove to true when using Move.NullMove. The goal is to get the other players Moves without making one my self. Is there any other way of doing that?
![image](https://github.com/SebLague/Chess-Challenge/assets/141482256/e09d1493-5148-45d8-a144-683aba6a45f9)

**Comment by SebLague** [comment]
The make move function ignores null moves. If you want to skip the turn, use the TrySkipTurn/ForceSkipTurn and UndoSkipTurn functions instead

**Comment by Gamaya0** [comment]
ok thanks
