### ISSUE TITLE
GetAllPieceLists is described as getting white pawns twice.

### ISSUE THREAD

**Issue by Alex-Huggett** [SebLague/Chess-Challenge#44]

**Comment by MinekPo1** [comment]
> Gets an array of all the piece lists. In order these are: Pawns(white), Knights (white), Bishops (white), Rooks (white), Queens (white), King (white), Pawns (black), Knights (black), Bishops (black), Rooks (black), Queens (black), King (black).

This doesn't seem to be the case.

**Comment by Alex-Huggett** [comment]
> This doesn't seem to be the case.
I am seeing:
PieceList[] Board.GetAllPieceLists()
Gets an array of all the piece lists. In order these are: Pawns(white), Knights (white), Bishops (white), Rooks (white), Queens (white), King (white), Pawns (white), Knights (black), Bishops (black), Rooks (black), Queens (black), King (black)
so perhaps this was fixed after my download?

**Comment by SebLague** [comment]
Fixed in v1.11 (external docs were correct, but the summary in the code was wrong)
