### ISSUE TITLE
GameMoveHistory bug

### ISSUE THREAD

**Issue by jebissey** [SebLague/Chess-Challenge#446]
1. c1g5 isn't possible
![2023-08-12_11h37_19](https://github.com/SebLague/Chess-Challenge/assets/8895244/8d0c4c3b-fd6d-4c23-aec1-39d3b39f2819)

**Comment by SebLague** [comment]
Test games start from a variety of different positions, so I assume this was a position where the c1 bishop was free to move to g5. The board class has a startFEN property you can look at to see the starting position.

**Comment by jebissey** [comment]
Thanks for your respond.

Because my bot sometimes loses all its pieces quickly, I'd like to replay the game manually to try to understand why. According to the api, I thought all the moves were in GameMoveHistory.
![2023-08-12_17h36_48](https://github.com/SebLague/Chess-Challenge/assets/8895244/60b0bb75-6b44-4835-9c3a-ac10324b2858)
![2023-08-12_17h49_54](https://github.com/SebLague/Chess-Challenge/assets/8895244/16c52aed-6f55-4100-9cdb-6601c5587df6)

It is possible to have missing first moves ?

If it is not I would have to store them by myself.

**Comment by jebissey** [comment]
During the MyBot vs EvilBot matches I wanted to record all the movements, but it's definitely not easy.
Where are the missing moves?
In previous games?
<img width="1655" alt="2023-08-14_11h41_25" src="https://github.com/SebLague/Chess-Challenge/assets/8895244/57067110-4e26-4844-b5f6-6fd40d61dbe8">

**Comment by SebLague** [comment]
During a match, the games are started from various opening/middlegame positions (which you can find in resources/Fens.txt file)
The starting moves don't exist in that case, the game is just begun from a custom fen string.

**Comment by jebissey** [comment]
ok.
So I added some code to replay the game manually
![2023-08-14_13h59_28](https://github.com/SebLague/Chess-Challenge/assets/8895244/4136801c-8645-4627-b10a-2a510796a3c3)
![2023-08-14_13h58_55](https://github.com/SebLague/Chess-Challenge/assets/8895244/c45a3543-9b70-4405-b40d-4ca0bd2b0dce)
