### ISSUE TITLE
Limit for memory allocation

### ISSUE THREAD

**Issue by CeniusM** [SebLague/Chess-Challenge#45]
Is there going to be a limit on how much data You can allocate during the game for things like a transposition table?

**Comment by CoolJWB** [comment]
This is an excellent question, I hope there won't be one, but I suspect there will be one.

**Comment by mcthouacbb** [comment]
@CoolJWB If there isn't a memory limit, then what's stopping someone from just allocating as much of system memory as possible and causing other programs to run out of memory, making them crash and lose the game?

**Comment by CeniusM** [comment]
Would Also be weird to have an arbitrary not known memory limit

**Comment by SebLague** [comment]
Memory limit is 256mb. Thanks for the question, that should have been in the rules from the start, but I've added it now!
