### ISSUE TITLE
Piece Lists not correctly updated after MakeMove()

### ISSUE THREAD

**Issue by Chrislee187** [SebLague/Chess-Challenge#46]
Am I missing something?

I'm trying to get at the piece lists after making a move but they don't seem to be updated.

I've boiled it down to the following simple example.

```
    public Move Think(Board board, Timer timer)
    {
        var from = new Square(0, 1);
        var to = new Square(0, 2);
        var moveString = $"{from.Name}{to.Name}";
        var move = new Move(moveString, board);
        board.MakeMove(move);

        var originalLocation = board.GetPiece(from);
        var newLocation = board.GetPiece(to);
        var allPieces = board.GetPieceList(PieceType.Pawn, true);

        Debug.Assert(allPieces.All(p => p.IsPawn)); // Fails, first "pawn" is null
        Debug.Assert(originalLocation.IsNull); // Fails still has the Pawn in it set to true
        Debug.Assert(!newLocation.IsNull);    // Fails, IsNull is true instead of IsPawn

        board.UndoMove(move);
        return move;
    }
```

**Comment by Parsek2047** [comment]
I have the same problem. Even after calling the MakeMove() function, the GetPiece() function (and I suppose any function that involves pieces) will return the position of pieces as if that function had never been called. I'm still searching for a quick fix but I think this is something Sebastian has to solve himself

**Comment by Chrislee187** [comment]
Ok, not just me going mad then ;), thanks.

I also debugged a little into it but also didn't find anything obvious in the time I had available.

**Comment by matt-winfield** [comment]
Also running into a similar issue with `board.GetAllPieceLists()` not updating correctly, some pieces after moves will become null or not be present:
![image](https://github.com/SebLague/Chess-Challenge/assets/15931560/3200edb7-65b7-4951-8b4d-e81f2c704e80)

**Comment by egordorichev** [comment]
I thought I was going mad, I've spent 2 hours debugging it...

![image](https://github.com/SebLague/Chess-Challenge/assets/7851390/62e0ea78-23ae-4e3a-9696-96179a2daf77)

**Comment by SebLague** [comment]
Hi, sorry about this bug, not sure how I managed to miss this! Will post a fix soon.

**Comment by SebLague** [comment]
Fixed in v1.1 Sorry again for the error!

**Comment by rafibayer** [comment]
Still getting this as of 1.14

**Comment by KermitThePog** [comment]
Getting it as well
