### ISSUE TITLE
is it possible for anyone to make this program run on .NET SKD 0.5 (just update)

### ISSUE THREAD

**Issue by nathan09rules** [SebLague/Chess-Challenge#460]
i have been stuck on this issue for 2 whole day and have given up as there are to many things that need changing for it to run.

**Comment by ryanheath** [comment]
Why would you want to run in on 5.0 while there is already 7.0 and 8.0 is around the corner? 😅

**Comment by nathan09rules** [comment]
How can I update

**Comment by ryanheath** [comment]
Check out [SDK 7.0.400](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)
There is a version for several OSes available.

**Comment by nathan09rules** [comment]
issue fixed

**Comment by nathan09rules** [comment]
done
