### ISSUE TITLE
i just started out what is this error and how do i fix it terminal issue

### ISSUE THREAD

**Issue by nathan09rules** [SebLague/Chess-Challenge#462]
C:\Users\Documents\Chess-Challenge-main (1)\Chess-Challenge-main\Chess-Challenge\src\My Bot\MyBot.cs(5,
17): error CS0161: 'MyBot.Think(Board, Timer)': not all code paths return a value [C:\User\Documents\Chess-Challenge-main (1)\Chess-Challenge-main\Chess-Challenge\Chess-Challenge.csproj]

**Comment by Edward-789** [comment]
It means that your `Think` function may not always return a move.

**Comment by jongdetim** [comment]
Google "not all code paths return a value c#"

**Comment by nathan09rules** [comment]
Thanks
