### ISSUE TITLE
Can’t open board

### ISSUE THREAD

**Issue by Coder2622** [SebLague/Chess-Challenge#469]
When copying “ cd C:\Users\MyName\Desktop\Chess-Challenge\Chess-Challenge “ into the terminal on visual studio code, I get an error message saying there is no such file or directory, despite downloading the project. Also, when typing “ dotnet run” I get an error saying there is not a project to run. I can navigate to the code window in visual studio code of chess-challenge.csproj

**Comment by jongdetim** [comment]
In the integrated terminal, you have to navigate and set your working directory to the project directory.

**Comment by Coder2622** [comment]
isn't `cd `C:\Users\MyName\Desktop\Chess-Challenge\Chess-Challenge`` what you use to do this? When I run this command I get the error " cd: no such file or directory: C:UsersMyNameDesktopChess-ChallengeChess-Challenge "

**Comment by jongdetim** [comment]
Try: `cd Chess-Challenge/Chess-Challenge`

if that doesn't work, type: `pwd` to see the path to the current working directory. Then copy it and paste it after `cd` and add the remaining parts of the path.

I recommend Googling terminal file system navigation for your OS.

**Comment by Coder2622** [comment]
Managed to fix it, had to do `cd /Users/MyName/Downloads/Chess-Challenge-main/Chess-Challenge` instead of `cd C:\Users\MyName\Desktop\Chess-Challenge\Chess-Challenge`

**Comment by jongdetim** [comment]
Yes, backslash is an escape character on macOS & Linux
