### ISSUE TITLE
Constructing a Board

### ISSUE THREAD

**Issue by iamthetoaster** [SebLague/Chess-Challenge#48]
It may be useful to have a documented method for constructing an arbitrary board, perhaps from a string where each character represents a square and each rank is represented by a line. Is this in the cards?

**Comment by iamthetoaster** [comment]
I just peered into the source code - might've been best to do that first! Looks like it is possible to construct a board from a FEN string, but not documented, so this is better described as a documentation issue than enhancement

**Comment by iamthetoaster** [comment]
Whoops - it is not possible to construct a board from a FEN string using the allowed namespaces. Is there a reason for this?

**Comment by EikeSchwass** [comment]
I'm also curious about this. It's a quite annoying that there appears to be no (allowed) board cloning support

**Comment by MinekPo1** [comment]
It seems like

```C#
new Board(board.board)
```

works.

**Comment by sten-code** [comment]
the thing i'm currently using is
```csharp
public Board CopyBoard(Board board)
{
    ChessChallenge.Chess.Board b = new ChessChallenge.Chess.Board();
    b.LoadPosition(board.GetFenString());
    return new Board(b);
}
```
But this technically isn't allowed. I think/hope Sebastian wouldn't care that much if thats the only thing you're using that for, because this one is basically required for any minimax algorithm.

**Comment by ZEvanderKarl** [comment]
I would love to clone a board without having to write my own deep cloning method... definitely let us know if this is allowed!

**Comment by EikeSchwass** [comment]
@sten-code you can work around that by always using pairs of MakeMove und UndoMove. MinMax often is implemented via recursion and works well in that case, but for many other cases it becomes a hassle really quickly

**Comment by SebLague** [comment]
Hi, I've added: public static Board CreateBoardFromFEN(string fen) to the board class in V1.1
Please note that this is quite slow, so I'd generally recommend using the MakeMove and UndoMove functions on the board provided in the think function instead.
