### ISSUE TITLE
Segmentation fault (core dumped) when launching Chess-Challenge v1.20 on Ubuntu 20.04

### ISSUE THREAD

**Issue by yuchuehw** [SebLague/Chess-Challenge#495]
**Issue Summary:**

The Chess-Challenge baseline code from the coding competition fails to run on my environment.

**Description:**

After cloning the Chess-Challenge repository and attempting to run the project using the provided commands (`dotnet run`), the program launches but then halts with a "Launching Chess-Challenge version 1.20" printed in the console.

I tried some other ways of launching the code under the direction of [this discussion post](https://github.com/SebLague/Chess-Challenge/discussions/3). I ran the following command `dotnet build` (I get the message"Build succeeded.")  then `dotnet bin/Debug/net6.0/Chess-Challenge.dll` again the program seems to run at first before halting this time showing `Launching Chess-Challenge version 1.20\nSegmentation fault (core dumped)`

**Environment:**

- **Operating System:** Ubuntu 20.04
- **.NET SDK Version:** 6.0.403
- **.NET Runtime Version:** 6.0.11
- **Additional Information:** I am running the code on replit.com in their basic C# environment and ran all the command in shell.

**Steps to Reproduce:**
1. (Optional) create a new repository using replit.com
1. Clone the repository: `git clone https://github.com/SebLague/Chess-Challenge`
1. Navigate to the project folder: `cd ./Chess-Challenge/Chess-Challenge`
1. Building using`dotnet build`
1. Attempt to run the file using `dotnet bin/Debug/net6.0/Chess-Challenge.dll`

**Actual Behavior:**

The program prints "Launching Chess-Challenge version 1.20" and then crashes with a "Segmentation fault (core dumped)" error.

**Expected Behavior:**

The Chess-Challenge program should run without errors, displaying the chess board as described in the competition instructions.

**Error Messages:**

```
Launching Chess-Challenge version 1.20
Segmentation fault (core dumped)
```

**Notes:**

I have verified that .NET SDK 6.0.403 is installed, and the issue persists even after attempting to rebuild the project and checking for dependencies.

**Comment by ryanheath** [comment]
What happens when you change step 5 into:

5. Run using `dotnet run`

You normally do not have to go to the bin folder to execute the program.

Also I would recommend to upgrade to the lastest .net SDK, there is really no need to stay on the older stuff.
See https://dotnet.microsoft.com/en-us/download/dotnet/8.0
