### ISSUE TITLE
XML debugging

### ISSUE THREAD

**Issue by Toby506** [SebLague/Chess-Challenge#5]
VS code says I "have no extension for debugging XML" does anyone know which extension I should download to solve this issue?

**Comment by Enestenssy** [comment]
I suggest you use something like visual studio. VS code i meant for a lightweight so it might not have the things your looking for, but im not sure.

**Comment by just-a-hriday** [comment]
It shouldn't matter. XML is used for some config files inside C# projects, and you don't ever need to debug it. You shouldn't ever need to edit them either, but if you do, you should be able to without a debugger.

**Comment by AggregateException** [comment]
I just used the 3rd extension in the list when I searched ".NET", it's called ".NET Extension Pack", it'll force you to download the latest SDK if you don't have it on your machine.
![image](https://github.com/SebLague/Chess-Challenge/assets/140182062/391b6019-974b-4318-abfa-97b0a1de87dc)

**Comment by BraveCaperCat2** [comment]
it's called "C# xml debugging tool" - i use VS code too.

**Comment by SebLague** [comment]
I'd say you can safely ignore this warning, you don't need to do anything with xml in this challenge.
