### ISSUE TITLE
How to use PlyCount

### ISSUE THREAD

**Issue by Magnus24112** [SebLague/Chess-Challenge#50]
C# is difficult

![image](https://github.com/SebLague/Chess-Challenge/assets/56786591/a0f2aa9c-8b92-47ea-b569-a662872d62c9)

**Comment by suity-yellowlab** [comment]
Use `board.PlyCount`
You are accessing the class (Capital letter) not the object variable.

**Comment by Magnus24112** [comment]
> 

Thx! It's working now :)
