### ISSUE TITLE
Project not valid Unity Hub

### ISSUE THREAD

**Issue by Devukth** [SebLague/Chess-Challenge#55]
When i open the project using Unity Hub it gives me an error that the project is not valid
![image](https://github.com/SebLague/Chess-Challenge/assets/78857657/7b2378b1-eb0c-4944-a83c-9b397e4ec1e9)

**Comment by Eduardo79Silva** [comment]
I believe you are not supposed to open this project in Unity but rather directly in Visual Studio. (Or another IDE of your choice but the project already has a Visual Studio solution).

**Comment by Devukth** [comment]
If that is true, how would I be able to test my project?

**Comment by Scrapmine** [comment]
Use visual studio 2022
