### ISSUE TITLE
How can I get opponents legal moves?

### ISSUE THREAD

**Issue by MACAYCZ** [SebLague/Chess-Challenge#56]

**Comment by MACAYCZ** [comment]
... `board.GetLegalMoves()` seams to return only my pieces.

**Comment by SebLague** [comment]
You'll need to make one of your legal moves on the board using the board.MakeMove() function so that it's the opponent's turn. Then call board.GetLegalMoves() to get the opponent's moves.

**Comment by MACAYCZ** [comment]
Aha, ok thank you:)
