### ISSUE TITLE
Lambdas Reduce Brain Capacity by 1 vs Return Statements

### ISSUE THREAD

**Issue by Kaipand** [SebLague/Chess-Challenge#57]
`public Move Think(Board board, Timer timer) => board.GetLegalMoves()[0];
`
results in 24 Bot Brain Capacity
`public Move Think(Board board, Timer timer)
    {
        return board.GetLegalMoves()[0];
    }`
results in 25 Bot Brain Capacity

Both return a value and have the same content, but using a return statement is penalized.

**Comment by Vanny-Chuck** [comment]
I noticed that too, I hope Sebastian finds it!

**Comment by MinekPo1** [comment]
While likely unintentional, I doubt this will be banned. Its a clever optimization of small functions and game changing as a) one token is not much and B) lambdas are more limited than regular functions.

**Comment by SebLague** [comment]
Yeah ideally this would give the same token count, but I agree with @MinekPo1 that it's not really a big deal and you're welcome to use it as a small optimization :)
