### ISSUE TITLE
How do I use the TargetsSquare?

### ISSUE THREAD

**Issue by SikamaMikado** [SebLague/Chess-Challenge#59]
targetsquare.TargetSquare();

It gives me Non-invocable member 'name' cannot be used like a method.
So how do I use it then

(I am sorry if this is a really simple question, but I have never programed anything in C#)

**Comment by ayush-india** [comment]
try to google it out brother

**Comment by ayush-india** [comment]
ss pls
@SikamaMikado

**Comment by SikamaMikado** [comment]
Ok nevermind it has to be used on a Square, not Move.
