### ISSUE TITLE
Mention time limit in the rules

### ISSUE THREAD

**Issue by leumasme** [SebLague/Chess-Challenge#6]
The rules currently mention no execution time limit for the bots.  
The program itself shows a 1 minute per side per game limit, but this should likely be included in the rules as well.

**Comment by anko** [comment]
1 minute is pretty long!

If everyone plays against everyone, total time taken scales with the square of the number of participants.

**Comment by SebLague** [comment]
I've added a section about this to the rules, thanks for the suggestion!

**Comment by leumasme** [comment]
> I've added a section about this to the rules

> Environment.StackTracks

Typo alert
