### ISSUE TITLE
How do I find which side (White/Black) MyBot is on?

### ISSUE THREAD

**Issue by Vanny-Chuck** [SebLague/Chess-Challenge#60]
I'm wondering if the opposite color of the king's starting position is the only way. If there is a easier/less token expensive way to check the side, I'd love to hear it!

**Comment by SebLague** [comment]
When the Think function is called you can check board.IsWhiteToMove

**Comment by Vanny-Chuck** [comment]
Thanks!

**Comment by Vanny-Chuck** [comment]
hey colud you check this:https://github.com/SebLague/Chess-Challenge/issues/57#issue-1816116031
