### ISSUE TITLE
Current .NET SDK not supported

### ISSUE THREAD

**Issue by FlorianButz** [SebLague/Chess-Challenge#62]
I have installed the .NET 6 SDK and tried to build the project but all I get is a message that says it couldn't build the project and this error:

![2023-07-21 19_18_24-Chess-Challenge - Microsoft Visual Studio](https://github.com/SebLague/Chess-Challenge/assets/75260616/bb9926da-31b5-491b-a62c-b852ca1187cd)

It says that the current installed .NET SDK dose not support .NET 6, however I installed the .NET 6 SDK. I also can't change the .NET target, since the dropdown is gray and empty.

I'm sorry if this is a stupid problem, I never opened someone else's project.

**Comment by Vanny-Chuck** [comment]
Which version of visual studio do you have?

**Comment by jiri132** [comment]
I had the same issue on .NET 4.0.1 on VS2019 but swapped it to VS2022 and got it working.

**Comment by Vanny-Chuck** [comment]
same

**Comment by FlorianButz** [comment]
I use visual studio 2019 but I'm updating it currently

**Comment by lythd** [comment]
it should work switching to vs 2022, i had that problem too since vs 2019 doesnt support .net 6.0

**Comment by FlorianButz** [comment]
One question, do I need to install the .NET application support package in the installer?

**Comment by FlorianButz** [comment]
Great, I've updated to VS 2022 and it works perfectly fine now, thanks :)
