### ISSUE TITLE
How do I get a castling move? 

### ISSUE THREAD

**Issue by Vanny-Chuck** [SebLague/Chess-Challenge#64]
i.e if(bd.HasQueensideCastleRight(bd.IsWhiteToMove) == true) return castleMove;

**Comment by MinekPo1** [comment]
Kingside:
```
new Move(bd.IsWhiteYoMove ? "e1g1" : "e8g8",bd)
```

Queenside:
```
new Move(bd.IsWhiteYoMove ? "e1b1" : "e8b8",bd)
```

Doesn't check if the move is legal though.

**Comment by mcthouacbb** [comment]
You can loop through all the moves in Board.getLegalMoves() and then check to see if the move is a castling move with Move.IsCastles
