### ISSUE TITLE
Getting a Directory Not Found Exception

### ISSUE THREAD

**Issue by JustA3DObject** [SebLague/Chess-Challenge#69]
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\OneDrive\Desktop\Chess-Challenge-main\src\My Bot\MyBot.cs'.

At location: Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs: line 218

**Comment by TheUnity42** [comment]
Chess-Challenge is nested inside the cloned repo, I pulled it out to be top level and changed 1 line (line 6, for me) in the .sln and it started working

**Comment by JustA3DObject** [comment]
Thanks a lot man I was almost considering to hard code the paths in ChallengeControllers .
