### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by BraveCaperCat2** [SebLague/Chess-Challenge#73]
Hi! I'm trying this challenge but i can't seem to open the c# code in unity like you did in the video, it says the project is not valid, but this may be because i'm using 2023.1.0a25 unity editor but i'm not sure.
I'm sure i'll make a great chess bot
I know what a token is since i read a book on the insides of computers (which is supposed to be a companion to a series of videos you pointed out in your first episode of your logic sim) which also described stuff like assembling assembly code and compiling high level code (i'm an expert in this stuff now)

**Comment by SebLague** [comment]
Hi, this isn't a Unity project, you need to open it in an IDE such as Visual Studio and build from there. Someone mentioned potentially porting the project to Unity, so keep an eye out for that if you'd prefer to work there #29

**Comment by BraveCaperCat2** [comment]
aw.. i thought you opened it in unity.
