### ISSUE TITLE
How to make a specific move

### ISSUE THREAD

**Issue by Magnus24112** [SebLague/Chess-Challenge#78]
In the documentation I found this:

new Move(string name, Board board)

But I must have misunderstood since it's not working

```
using System;
using ChessChallenge.API;

 public class MyBot : IChessBot
{
    public Move Think(Board board, Timer timer)
    {
        Move[] moves = board.GetLegalMoves();
        if (board.PlyCount == 1) {
            return new Move("e2e4", Board board);
        }
        else {
            return moves[0];
        }
    }
}

**Comment by FismanMaxim** [comment]
Well, the board is passed as an argument. It should be
`return new Move("e2e4", board);` instead of `return new Move("e2e4", Board board);`
There's no need to create one more variable!

(by the way, plyCounter starts with 0, so "e2e4" can never be the 1st move)

**Comment by Magnus24112** [comment]
Thank you :)

**Comment by Vanny-Chuck** [comment]
vvvvvvvvvvv
return new Move("e2e4", Board board);
