### ISSUE TITLE
Issue With Running The Program

### ISSUE THREAD

**Issue by jirkaORIGINAL** [SebLague/Chess-Challenge#8]
So i just opened the program and when i try to run it it says "Please select a valid startup item!" its first time running vs on my new laptop so idk what i am doing.
Thanks.
![image](https://github.com/SebLague/Chess-Challenge/assets/88187971/0dd31a65-9b82-4665-93fe-280150857403)
It just says this

**Comment by Brassflautist** [comment]
You need to go to Project Debug and in the general Paragraph click the blue link of "Open debug launch profiles UI" and then browse source for the Executable then navigate to Chess-Challenge-main\Chess-Challenge\bin\Debug\net6.0\Chess-Challenge.exe. This should fix your problem it did for me

**Comment by jirkaORIGINAL** [comment]
> 

could you give more instruction im a dumbass

**Comment by CREAsTIVE** [comment]
> > 
> 
> could you give more instruction im a dumbass

try this
![image](https://github.com/SebLague/Chess-Challenge/assets/62616308/be5f0e9e-b020-4202-9f92-a3e70ac03a12)

**Comment by jirkaORIGINAL** [comment]
> > > 
> > 
> > 
> > could you give more instruction im a dumbass
> 
> try this ![image](https://user-images.githubusercontent.com/62616308/255206176-be5f0e9e-b020-4202-9f92-a3e70ac03a12.png)

no i just opened the file wrong 😑
