### ISSUE TITLE
Can I use System.Timers.Timer?

### ISSUE THREAD

**Issue by FismanMaxim** [SebLague/Chess-Challenge#80]
I don't quite understand if I can use System.Timers.Timer. The rules contain a list of 5 namespaces that I can use, but does that mean that anything other than that just can't be included in the "using" section or can't be used at all? If the latter, then how to time the search?

**Comment by Vanny-Chuck** [comment]
"Timer timer" is passed into Think() as an argument.
![image](https://github.com/SebLague/Chess-Challenge/assets/140184612/919a41b2-3a04-4f30-b940-51c056ed571a)

**Comment by FismanMaxim** [comment]
@Vanny-Chuck Ohhh! I knew the Timer was passed, but I completely forgot about the `MillisecondsElapsedThisTurn` property of the Timer, despite it was in the documentation! It, obviously, stores how many milliseconds passed since the beginning of the search.
