### ISSUE TITLE
msbuild error msg

### ISSUE THREAD

**Issue by BoboNovi** [SebLague/Chess-Challenge#81]
"msbuild : The term 'msbuild' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path"
This is the error msg I get whenever I try to build the project and I dont know how to fix it

**Comment by RiedleroD** [comment]
install the dotnet sdk, msbuild is part of that

**Comment by BoboNovi** [comment]
> install the dotnet sdk, msbuild is part of that

I will try to fix it now with Chat GPT I already installed .NET 6.0

**Comment by BoboNovi** [comment]
I have no idea how but I installed VS 2022 and used that instead ov VS code and it works now
