### ISSUE TITLE
Pieces not showing up on the board. Bug?

### ISSUE THREAD

**Issue by Draki8888** [SebLague/Chess-Challenge#82]
I have encounterd a bug where I cannot see any of the pieces when I start the program.

I have not touched anything of the code or the resources and for some weird reason as soon as I run the program I cannot see any of the pieces what so ever. I got no idea what I am supposed to do or how to fix it and very lost. 

if anyone is able to help in any way it would be wonderful and grately appriciated.

**Comment by MathabsUnity** [comment]
Can you provide a screenshot?

**Comment by Draki8888** [comment]
![image](https://github.com/SebLague/Chess-Challenge/assets/94855217/bd7015cc-0b3c-4dd9-905a-460a7164b138)
Here you go.

**Comment by MathabsUnity** [comment]
Perhaps try downloading the starter files again and see if that works?

**Comment by Draki8888** [comment]
> Perhaps try downloading the starter files again and see if that works?

I have tried, two times actually. didn't work. maybe something with my system

**Comment by MathabsUnity** [comment]
Try changing the font to be the regular font?

**Comment by Draki8888** [comment]
The issue is that the project's path contains non english characters (hebrew in my case) .
