### ISSUE TITLE
Board.MakeMove() not working

### ISSUE THREAD

**Issue by MathabsUnity** [SebLague/Chess-Challenge#83]
When I use Board.MakeMove(), it gives me an error in a MovePiece() function:

Exception Thrown

System.NullReferenceException: 'Object reference not set to an instance of an object'

pieceLists[] was null.

My Code:

```
    public Move Think(Board board, Timer timer)
    {
        Move[] moves = board.GetLegalMoves();
        float highestEval = int.MinValue;
        Move bestMove = Move.NullMove;
        foreach (Move item in moves)
        {
            board.MakeMove(item);
            float eval = EvaluatePosition(board);
            if (eval > highestEval)
            {
                bestMove = item;
                highestEval = eval;

            }
        }

        return bestMove;
    }

    public float EvaluatePosition(Board board)
    {
        PieceList[] pieces = board.GetAllPieceLists();
        return ((pieces[0].Count + (pieces[1].Count + pieces[2].Count) * 3 + pieces[3].Count * 5 + pieces[4].Count * 9) - (pieces[0].Count + (pieces[1].Count + pieces[2].Count) * 3 + pieces[3].Count * 5 + pieces[4].Count * 9)) * (board.IsWhiteToMove ? 1 : -1);
    }
```

**Comment by MathabsUnity** [comment]
![image](https://github.com/SebLague/Chess-Challenge/assets/110788706/757f7101-8824-4995-a29f-e75f50c53488)
![image](https://github.com/SebLague/Chess-Challenge/assets/110788706/68dee254-77e5-4736-8134-2c39f6c2d4f9)

**Comment by AugsEU** [comment]
You aren't resetting your board position in that loop. So what you are really doing is making all the legal moves in consecutive order, and that is probably not allowed. This looks like a bug with your code.

**Comment by Odin7094** [comment]
Follow it with a UndoMove

**Comment by nikita-demidov** [comment]
Hello!
Board::MakeMove(moveX) puts the board into a position following the move you put as an argument. To try another move, you have to call the UndoMove(moveX) method. This is also documented in the [documentation](https://seblague.github.io/chess-coding-challenge/documentation/) linked in the README.md.
Good Luck!

**Comment by MathabsUnity** [comment]
Thanks everyone!

I thought that I had already put a UndoMove, thanks again! :)
