### ISSUE TITLE
Using Visual studio for Unity, how can i detach it to run the file?

### ISSUE THREAD

**Issue by akamegakira** [SebLague/Chess-Challenge#84]
I have been using visual studio only for unity, and when i want to run the script, i only have the option "attach" next to the green triangle.
Does anyone know how to fix it?

**Comment by mcthouacbb** [comment]
Did you open the project by double clicking the solution file(Chess-Challenge.sln)? If not, try doing that.

**Comment by akamegakira** [comment]
No, but no i did and it works. Its the first time i participate in something like that :) 
Thanks!

**Comment by CharlesBeverly** [comment]
> Did you open the project by double clicking the solution file(Chess-Challenge.sln)? If not, try doing that.

Im having the same problem, but when opening the project through the Chess-Challenge.sln it simply brings up a blank Vs code screen that does nothing, how is it supposed to work and how is one supposed to properly build and run their code, the directions on the read me simply read "build and run" without any further instructions and being new to the area this is very hard to understand

**Comment by ufrshubham** [comment]
> it simply brings up a blank Vs code screen that does nothing,

@CharlesBeverly You need to use Visual Studio. VS and VSCode are two very different software packages. There are ways to make this work with VSCode too, but using VS will just reduce the friction.

**Comment by ufrshubham** [comment]
@akamegakira if your original problem has been resolved can you close this issue?

**Comment by akamegakira** [comment]
@ufrshubham i have the same thing, but i am new too, so i supposed that this is how it was supposed to be since if i press the triangle it runs. Are we certain that a .sln file should have something appearing as a code file?
Sorry i cant help, i am a newbie😅.

**Comment by akamegakira** [comment]
@ufrshubham i finally think i had success!!!
The thing is that as i understand it, a .sln file is the environment, much like unity.
So what you can then do is open the other scripts after you have the sln file opened and you will have the scripts to run inside the desired environment.
so in essence:
1. open the sln file and leave it running
2. open any script you want from the challenge and modify it
3. press the triangle that now says chess-challenge

the code is stored in the .cs files, so you can change and read whatever you want
But remember we are to only submit the MyBot.cs script

**Comment by ufrshubham** [comment]
@akamegakira glad that you figured it out. Here are few more details about `.sln`.

Visual Studio is not just a code editor, it has a lot more features to it. It be used to open and modify a single file, but in most cases any kind of application is made up of multiple files. For example, a Unity project consists of multiple Scriptable Objects, Prefabs, Scenes, etc, you get the point. 

Similar to that an application written in C# also consists of multiple C# files (aka source code or code base or project). To make it easier to maintain, build and debug this source code, you use IDEs (integrated development environment). Visual Studio is one of such IDEs. To open a project, an IDE needs to know all the files, their locations, their type and a million other things. All this information is stored in IDE specific project files. For Visual Studio, `.sln` is that project file (there are a few more too, but sln is the most important one). 

Btw, `sln` stands for `Solution` and a single solution can contain multiple projects too. Also, this is not specific to just a C# project, any kind of project created with Visual Studio will have a solution file. I might have oversimplified things but you get the gist of it 😄. More details about Visual Studio solution can be found [here](https://learn.microsoft.com/en-us/visualstudio/extensibility/internals/solutions-overview?view=vs-2022).

Also, this is very common for a lot software packages. For example, 
- Unreal uses `.uproject`
- Godot uses `.godot`
