### ISSUE TITLE
Add alternative installation/build method in README

### ISSUE THREAD

**Issue by impopular-guy** [SebLague/Chess-Challenge#85]
For people who have never used VS or C# or .NET (like me ;-;), it would be better to add some more alternatives and direct build instructions:

- Install .NET 6 (same link given on README)
- open terminal/cmd
- `cd path\to\Chess-Challenge\Chess-Challenge.csproj`
- `dotnet run`

Now you can use any code editor.

**Comment by RiedleroD** [comment]
ah wow thank you. I was trying stuff with manually running msbuild, which didn't work.

honestly, that should be in the Readme.

**Comment by SatvikSrinivas** [comment]
Thank you this was very helpful!

**Comment by SebLague** [comment]
Thanks for sharing these instructions. I've added a link to this in the readme.
