### ISSUE TITLE
How to use IsInCheckmate

### ISSUE THREAD

**Issue by Magnus24112** [SebLague/Chess-Challenge#86]
I want to check every move my opponent can make to see if it checkmates me so I can prevent that but I don't know how to use IsInCheckmate

```

{
    public Move Think(Board board, Timer timer)
    {
        Move[] moves = board.GetLegalMoves();
        board.TrySkipTurn();
        foreach (Move move in moves)
        {
            if (bool board.IsInCheckmate)
            {
                //Prevent checkmate
            }
        }
    }
}

**Comment by Vanny-Chuck** [comment]
bool MoveIsCheckmate(Board board, Move move)
    {
        board.MakeMove(move);
        bool isMate = board.IsInCheckmate();
        board.UndoMove(move);
        return isMate;
    }

**Comment by Magnus24112** [comment]
Thx!
