### ISSUE TITLE
How to test on 1000 games?

### ISSUE THREAD

**Issue by zzzzz151** [SebLague/Chess-Challenge#88]
Running MyBot vs EvilBot is very slow, is there a way to run the 1000 games as fast as possible and get the results?

**Comment by Azukee** [comment]
The method `OnMoveChosen` in the ChallengeController.cs has a minimum delay. You can change it to make the bot run slower or faster, so you can see what's happening. I've not tried making it faster than the current minDelay.

**Comment by mcthouacbb** [comment]
In src/Framework/Application/Core/Settings.cs, there's a variable called "GameDurationMilliseconds". Changing this variable should change the total amount of time available to both bots(So, if you want a shorter game you can change it to something like 15 or 10 seconds)

**Comment by zzzzz151** [comment]
@Azukee Thank you, your solution works, lowering minDelay makes the games play out much faster!

@mcthouacbb I think your solution wouldn't work since the move animations would take the same (slow) time.

**Comment by WhiteMouse1** [comment]
I use CheatEngine to speedhack the built application 100 times.
No timeouts for either of bots, but I have zero clue whether am I breaking something horribly.
It gets up to 1 full game per second of real time at 200 speedup, but it does not become faster with higher values.
My guess is the speedhack mostly speeds up UI, with actual logic being untouched.

**Comment by impopular-guy** [comment]
I found a very hacky way to speed up 1000 runs, just increase FPS to some high number,            `src\Framework\Application\Core\Program.cs:28 Raylib.SetTargetFPS(1000);`
