### ISSUE TITLE
how do i specify promotion type

### ISSUE THREAD

**Issue by TritionGames** [SebLague/Chess-Challenge#89]
when i try to always make it promote to a queen, i keep getting errors

**Comment by dr-vortex** [comment]
see `Move.PromotionPieceType`

**Comment by TritionGames** [comment]
> see `Move.PromotionPieceType`
how do i use it though?

**Comment by dr-vortex** [comment]
When you fetch the array of all valid moves, there will be a different move for each promotion type. You then return the move with the desired promotion type from `Think`.

**Comment by Coldwings21** [comment]
What is the sentax for setting the promotion to a queen? (assuming the move in question is a promotion)

**Comment by JoaoMariaSantos** [comment]
> What is the sentax for setting the promotion to a queen? (assuming the move in question is a promotion)

It should be something like:
`if ((int)move.PromotionPieceType == 5) return move;`

PieceType is an enum, and queen is 5
`public enum PieceType
    {
        None,//0   
        Pawn,//1   
        Knight,//2   
        Bishop,//3   
        Rook,//4   
        Queen,//5   
        King//6   
    }`

**Comment by RaxMoth** [comment]
This is also possible 
`if (move.IsPromotion && (int)move.PromotionPieceType == 5)
            {
                return move;
            }`

**Comment by TritionGames** [comment]
thanks :DDDDD

**Comment by dr-vortex** [comment]
@JoaoMariaSantos @RaxMoth @TritionGames 

Instead of casting to int, you can just compare it to a piece type:
```cpp
if (move.PromotionPieceType == PieceType.Queen)
{
    return move;
}
```
