### ISSUE TITLE
Does GetLegalMoves() check for checks?

### ISSUE THREAD

**Issue by Kickerflix** [SebLague/Chess-Challenge#9]
Does the GetLegalMoves() method check if the king is in check? Because my Bot only picks moves out of the GetLegalMoves() array and made an illegal move, because it tried to move something else while to king was in check. (And no the move did not resolve the check)

**Comment by Enestenssy** [comment]
You could use the IsInCheck() function to check if the king is in fact in check.

**Comment by Kickerflix** [comment]
But it doesn't give any answers to the check.

**Comment by Enestenssy** [comment]
What do you mean by that? That function returns a bool value.

**Comment by SebLague** [comment]
Yes the GetLegalMoves function accounts for check. Do you happen to have a screenshot of the position that this occurred in so I can take a look?

**Comment by Kickerflix** [comment]
I just realized the actual mistake. I tried to do a move that was null, because I chose the wrong array to pick a move from. Sorry for the trouble.

**Comment by SebLague** [comment]
No worries, thanks for letting me know!
