### ISSUE TITLE
castling

### ISSUE THREAD

**Issue by MayonnaiseButWrong** [SebLague/Chess-Challenge#90]
was looking through the api, and this doesn't look right...
![image](https://github.com/SebLague/Chess-Challenge/assets/123032187/da3131fd-253b-400f-af37-b3c84963bd41)

**Comment by dr-vortex** [comment]
See #64

**Comment by MayonnaiseButWrong** [comment]
yea its actually fine..
i think im blind istg

**Comment by dr-vortex** [comment]
Please close the issue
