### ISSUE TITLE
Add rank and file labels to visual board

### ISSUE THREAD

**Issue by dr-vortex** [SebLague/Chess-Challenge#91]
Chess.com:
<img src="https://github.com/SebLague/Chess-Challenge/assets/75621402/28124b2a-8803-46e9-8c08-51f2567e6167" width="500" />

Chess challenge:
<img src="https://github.com/SebLague/Chess-Challenge/assets/75621402/21d276f6-9a49-4600-8122-ccbbdaba6834" width="500" />

It would be nice to have the ranks and files labeled.

**Comment by SebLague** [comment]
Added in V1.11 thanks to #133

**Comment by gamma-delta** [comment]
[^_^]
