### ISSUE TITLE
I can't figure out a way to get the legalMoves of the opponent.

### ISSUE THREAD

**Issue by Diamoundz** [SebLague/Chess-Challenge#96]
Is there a way to get a list without having to program the whole legal move check for the opponent as well ?

**Comment by Vanny-Chuck** [comment]
SkipMove(), that'll give u the enemy perspective! 🖥😀
_____________________________________________________⊤⊤⊤______

**Comment by V-bot29** [comment]
Im stuck on the same Problem, SkipMove is not mentioned in the Documentation though, i dont understand what you mean :(

**Comment by leohilbert** [comment]
```
if (board.TrySkipTurn())
{
    Move[] opponentMoves = board.GetLegalMoves();
    board.UndoSkipTurn();
}
```

`TrySkipTurn` only fails (aka returns false), if you're currently in check (since the game would be over haha)

**Comment by V-bot29** [comment]
Thank you, ill give it a try

**Comment by Diamoundz** [comment]
! I FOUND THE ISSUE ! , when using board.makeMove() it will automatically skip turn after making the move. This wasn't specified and was a bit confusing at first.
