### ISSUE TITLE
Suggestion: Make Token Length Categories: 2k, 3k, 4k and 10k

### ISSUE THREAD

**Issue by Logophoman** [SebLague/Chess-Challenge#97]
1000 Tokens is quite tricky and indeed a fun challenge! 

However what do you think if people could hand in longer code, such as 2k, 3k, 4k and 10k, we could have these compete among each other and also see how they'd play against each other. Could be fun 😊 

What does everyone think?

**Comment by Supersamu** [comment]
IMO it is a good idea to not split the challenge up so much. I think the limit was chosen to allow people who are new to programming or C# to participate without needing to write a lot of code. I am sure the consideration for multiple tracks has been made before publishing the repo and the video.

**Comment by 101dal** [comment]
I think it's a quite interesting idea but the goal of the challenge is to limit people and force them to find funny ideas to overcome this token limit

**Comment by lucasmeneghin** [comment]
I think 2 categories could be nice, more than that would split too much

**Comment by SebLague** [comment]
Yeah I do think it's a cool idea! I want to keep things simple with just a single category this time, but if people are interested in more challenges in the future, I'll definitely consider doing something like this.
